from __future__ import annotations

from pathlib import Path
from zipfile import ZipFile

from tools.bambuddy.run_forensics_import_queue import (
    assess_entry,
    build_synthetic_candidate,
    build_synthetic_manifest,
    queue_summary,
    read_manifest_triage_entries,
    update_source_manifest,
)
from tools.bambuddy.gcode_forensics_viewer import write_json, load_json


def _write_zip(path: Path, members: dict[str, str | bytes]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w") as archive:
        for name, content in members.items():
            archive.writestr(name, content)
    return path


def _write_manifest(path: Path, entry: dict[str, object]) -> Path:
    payload = {
        "candidates": [],
        "secondary_artifact_analysis": {
            "cache_secondary_artifacts": {
                "manual_triage_decisions": {
                    "entries": [entry]
                }
            }
        },
    }
    write_json(path, payload)
    return path


def test_runner_assess_entry_marks_sliced_keep_item_ready(tmp_path: Path) -> None:
    source_path = _write_zip(
        tmp_path / "Dragon.gcode.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    entry = {
        "gcode_name": "Dragon_plate_1.gcode",
        "disposition": "Keep",
        "selected_source_path": str(source_path),
        "source_files": [
            {
                "path": str(source_path),
                "source_type": "bambu_studio_exported_sliced_3mf",
                "canonical_archive_ready": True,
                "suggested_import_mode": "create_archive_upload",
                "modified_at": "2026-04-12T19:16:06Z",
            }
        ],
        "import_plan": {
            "mode": "create_archive_upload",
            "inferred_started_at": "2026-04-12T19:16:06Z",
            "inferred_created_at": "2026-04-12T19:16:06Z",
        },
    }

    item = assess_entry(entry)

    assert item.status == "ready"
    assert item.mode == "create_archive_upload"
    assert item.started_at == "2026-04-12T19:16:06Z"

    candidate = build_synthetic_candidate(item)
    assert candidate["source_type"] == "bambu_studio_exported_sliced_3mf"
    assert candidate["timestamp_evidence"]["timestamp_candidates"][0]["source"] == "forensics:started_at"


def test_runner_assess_entry_blocks_raw_gcode_wrap_path(tmp_path: Path) -> None:
    source_path = tmp_path / "Recovered_plate_1.gcode"
    source_path.write_text("; generated by Bambu Studio\n", encoding="utf-8")
    entry = {
        "gcode_name": "Recovered_plate_1.gcode",
        "disposition": "Keep",
        "selected_source_path": str(source_path),
        "source_files": [
            {
                "path": str(source_path),
                "source_type": "raw_gcode_file",
                "canonical_archive_ready": False,
                "suggested_import_mode": "wrap_raw_gcode_experimental",
                "modified_at": "2026-04-11T19:16:06Z",
                "header_metadata": {"filament_slots": "0"},
            }
        ],
        "import_plan": {
            "mode": "wrap_raw_gcode_experimental",
            "inferred_started_at": "2026-04-11T19:16:06Z",
        },
    }

    item = assess_entry(entry)

    assert item.status == "blocked"
    assert any("filament slot-to-type/color mapping" in row for row in item.missing_requirements)


def test_runner_can_read_writeback_and_update_manifest_results(tmp_path: Path) -> None:
    source_path = _write_zip(
        tmp_path / "Bat.gcode.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest_path = _write_manifest(
        tmp_path / "manifest.json",
        {
            "gcode_name": "Bat_plate_1.gcode",
            "disposition": "Keep",
            "selected_source_path": str(source_path),
            "source_files": [
                {
                    "path": str(source_path),
                    "source_type": "bambu_studio_exported_sliced_3mf",
                    "canonical_archive_ready": True,
                    "suggested_import_mode": "create_archive_upload",
                    "modified_at": "2026-04-12T19:16:06Z",
                }
            ],
            "import_plan": {
                "mode": "create_archive_upload",
                "inferred_started_at": "2026-04-12T19:16:06Z",
                "inferred_created_at": "2026-04-12T19:16:06Z",
            },
        },
    )

    entries = read_manifest_triage_entries(manifest_path)
    assert len(entries) == 1
    item = assess_entry(entries[0])
    synthetic = build_synthetic_manifest([item], batch_id="forensics-test")
    synthetic_manifest_path = tmp_path / "synthetic.json"
    write_json(synthetic_manifest_path, synthetic)

    synthetic_entry = synthetic["candidates"][0]
    backfill_result = {
        "result": {
            "results": [
                {
                    "entry_id": synthetic_entry["entry_id"],
                    "status": "uploaded_and_annotated",
                    "reason": "Archive created from manifest candidate.",
                    "created_archive_id": 612,
                    "matched_archive_id": None,
                }
            ]
        },
        "result_path": str(tmp_path / "result.json"),
    }
    update_source_manifest(
        manifest_path,
        [item],
        synthetic_manifest_path=synthetic_manifest_path,
        backfill_result=backfill_result,
        repair_results={"Bat_plate_1.gcode": {"applied": True}},
    )

    updated = load_json(manifest_path)
    runner = updated["secondary_artifact_analysis"]["cache_secondary_artifacts"]["manual_triage_decisions"]["entries"][0]["import_runner"]
    assert runner["queue_status"] == "ready"
    assert runner["created_archive_id"] == 612
    assert runner["runtime_repair"]["applied"] is True

    summary = queue_summary([item])
    assert summary["counts"]["ready"] == 1