from __future__ import annotations

from pathlib import Path
from zipfile import ZipFile
import json

from tools.bambuddy.folder_3mf_catalog_state import CatalogStateStore, merge_manifest_with_state
from tools.bambuddy.folder_3mf_catalog_viewer import CatalogDataset, render_page
from tools.bambuddy.generate_folder_3mf_catalog import build_manifest
from tools.bambuddy.reconcile_folder_3mf_catalog import reconcile_manifest
from tools.bambuddy.run_folder_3mf_catalog_import import main as runner_main, run_catalog_import, upsert_recovery_note


def _write_zip(path: Path, members: dict[str, str | bytes]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w") as archive:
        for name, content in members.items():
            archive.writestr(name, content)
    return path


def test_catalog_state_store_persists_export_workflow_and_import_plan(tmp_path: Path) -> None:
    state_path = tmp_path / "state" / "catalog_state.json"
    store = CatalogStateStore(state_path)

    entry = store.patch(
        "REC-001",
        {
            "disposition": "Keep",
            "manual_tags": ["historical", "needs-review"],
            "selected_archive_id": 55,
            "export_workflow": {
                "status": "needs_export",
                "target_export_folder": "C:/work/exports/sliced",
                "target_export_filename": "Widget_plate_1.gcode.3mf",
            },
            "import_plan": {
                "mode": "create_archive_upload",
                "inferred_started_at": "2026-04-20T10:00:00+00:00",
                "notes": "Use saved timestamp as starting point.",
            },
        },
    )

    assert entry["disposition"] == "Keep"
    assert entry["export_workflow"]["status"] == "needs_export"
    reloaded = CatalogStateStore(state_path)
    assert reloaded.get("REC-001") is not None
    assert reloaded.get("REC-001")["import_plan"]["mode"] == "create_archive_upload"


def test_reconcile_manifest_marks_exact_hash_matches_as_already_represented(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    model_path = _write_zip(
        source_root / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    candidate = manifest["candidates"][0]
    archives = [
        {
            "id": 123,
            "content_hash": candidate["source_sha256"],
            "print_name": "Widget",
            "created_at": candidate["best_inferred_print_time"],
        }
    ]

    reconciled = reconcile_manifest(manifest, archives, name_threshold=0.6, time_window_hours=72)

    updated = reconciled["candidates"][0]
    assert updated["reconciliation_status"] == "already_represented"
    assert updated["selected_archive_id"] == 123
    assert updated["matched_archive_ids"] == [123]


def test_reconcile_manifest_uses_name_and_saved_time_for_likely_match(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Projects" / "Widget Prototype.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    candidate = manifest["candidates"][0]
    archives = [
        {
            "id": 77,
            "print_name": "Widget Prototype plate 1",
            "created_at": candidate["best_inferred_print_time"],
        }
    ]

    reconciled = reconcile_manifest(manifest, archives, name_threshold=0.3, time_window_hours=72)

    updated = reconciled["candidates"][0]
    assert updated["reconciliation_status"] == "likely_represented"
    assert updated["selected_archive_id"] == 77
    assert updated["archive_name_match"] is not None


def test_viewer_dataset_merges_state_and_renders_export_status(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Widget.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    state_path = tmp_path / "state" / "catalog_state.json"
    store = CatalogStateStore(state_path)
    record_id = manifest["candidates"][0]["record_id"]
    store.patch(
        record_id,
        {
            "disposition": "Investigate",
            "export_workflow": {
                "status": "needs_export",
                "target_export_folder": "C:/work/exports/sliced",
            },
        },
    )
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(__import__("json").dumps(manifest, indent=2), encoding="utf-8")
    dataset = CatalogDataset(manifest_path, state_path)

    page = render_page(dataset, "all", record_id)

    assert "Folder 3MF Catalog Viewer" in page
    assert "needs_export" in page
    assert "Investigate" in page
    assert "C:/work/exports/sliced" in page


def test_viewer_dataset_update_state_persists_edits(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Widget.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    dataset = CatalogDataset(manifest_path, state_path)
    record_id = manifest["candidates"][0]["record_id"]

    updated = dataset.update_state(
        record_id,
        {
            "disposition": "Keep",
            "manual_tags": ["historical"],
            "import_plan": {"mode": "attach_source_only", "provenance_tag_mode": "notes_only"},
        },
    )

    assert updated["state"]["disposition"] == "Keep"
    assert updated["state"]["import_plan"]["mode"] == "attach_source_only"
    persisted = CatalogStateStore(state_path).get(record_id)
    assert persisted is not None
    assert persisted["manual_tags"] == ["historical"]


def test_viewer_dataset_runner_action_returns_inspect_payload(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    store = CatalogStateStore(state_path)
    record_id = manifest["candidates"][0]["record_id"]
    store.patch(record_id, {"disposition": "Keep", "import_plan": {"mode": "create_archive_upload"}})
    dataset = CatalogDataset(manifest_path, state_path)

    payload = dataset.run_queue_action("inspect")

    assert payload["summary"]["counts"]["ready"] == 1
    assert payload["dry_run"] is None


def test_viewer_runner_action_uses_custom_dry_run_manifest_path(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    record_id = manifest["candidates"][0]["record_id"]
    CatalogStateStore(state_path).patch(record_id, {"disposition": "Keep", "import_plan": {"mode": "create_archive_upload"}})
    dataset = CatalogDataset(manifest_path, state_path)
    custom_path = tmp_path / "reports" / "viewer-dry-run.json"

    payload = dataset.run_queue_action("dry-run", synthetic_manifest_path=str(custom_path))

    assert payload["synthetic_manifest_path"] == str(custom_path.resolve())
    assert custom_path.exists()


def test_viewer_runner_action_requires_confirmation_for_run_backfill(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    record_id = manifest["candidates"][0]["record_id"]
    CatalogStateStore(state_path).patch(record_id, {"disposition": "Keep", "import_plan": {"mode": "create_archive_upload"}})
    dataset = CatalogDataset(manifest_path, state_path)

    try:
        dataset.run_queue_action("run-backfill", base_url="http://bambuddy.local", printer_id=1)
    except ValueError as exc:
        assert "explicit confirmation" in str(exc)
    else:
        raise AssertionError("run-backfill should require explicit confirmation")


def test_viewer_runner_action_forwards_confirmed_run_backfill_options(tmp_path: Path, monkeypatch) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    record_id = manifest["candidates"][0]["record_id"]
    CatalogStateStore(state_path).patch(record_id, {"disposition": "Keep", "import_plan": {"mode": "create_archive_upload"}})
    dataset = CatalogDataset(manifest_path, state_path)
    captured: dict[str, object] = {}

    def fake_run_catalog_import(**kwargs):
        captured.update(kwargs)
        return {"summary": {"counts": {"ready": 1}}, "synthetic_manifest_path": str(kwargs.get("synthetic_manifest_path")), "dry_run": None, "backfill": {"status": "ok"}, "source_attachments": {}, "provenance_updates": {}}

    monkeypatch.setattr("tools.bambuddy.folder_3mf_catalog_viewer.run_catalog_import", fake_run_catalog_import)

    payload = dataset.run_queue_action(
        "run-backfill",
        synthetic_manifest_path=str(tmp_path / "custom-backfill.json"),
        base_url="http://bambuddy.local",
        printer_id=1,
        api_key="secret",
        backfill_action="Upload",
        confirmed=True,
    )

    assert payload["backfill"]["status"] == "ok"
    assert captured["action"] == "run-backfill"
    assert captured["base_url"] == "http://bambuddy.local"
    assert captured["printer_id"] == 1
    assert captured["api_key"] == "secret"
    assert captured["backfill_action"] == "Upload"
    assert captured["write_back_results"] is True


def test_merge_manifest_with_state_attaches_state_by_record_id() -> None:
    manifest = {
        "candidates": [{"record_id": "REC-1", "relative_path": "widget.3mf"}],
    }
    state = {
        "entries": [{"record_id": "REC-1", "disposition": "Keep"}],
    }

    merged = merge_manifest_with_state(manifest, state)

    assert merged["candidates"][0]["state"]["disposition"] == "Keep"


def test_upsert_recovery_note_replaces_own_block_without_disturbing_other_blocks() -> None:
    existing = "[RECOVERY_AUDIT_V1]\n{\"replaced_by_archive_id\":200}\n\n[FOLDER_CATALOG_RECOVERY_V1]\n{\"old\":true}\n\n+>{\"src\":\"afs\"}"

    merged = upsert_recovery_note(existing, {"record_id": "REC-1", "recovery_source": "folder_3mf_catalog"})

    assert "[RECOVERY_AUDIT_V1]" in merged
    assert "+>{\"src\":\"afs\"}" in merged
    assert '"record_id": "REC-1"' in merged or '"record_id":"REC-1"' in merged
    assert '"old":true' not in merged


def test_folder_catalog_runner_dry_run_emits_create_and_attach_actions(tmp_path: Path, monkeypatch, capsys) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "SlicedReady.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    _write_zip(
        source_root / "SourceOnly.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    store = CatalogStateStore(state_path)
    by_path = {row["relative_path"]: row for row in manifest["candidates"]}
    store.patch(by_path["slicedready.3mf"]["record_id"], {"disposition": "Keep", "import_plan": {"mode": "create_archive_upload"}})
    store.patch(by_path["sourceonly.3mf"]["record_id"], {"disposition": "Keep", "selected_archive_id": 77, "import_plan": {"mode": "attach_source_only"}})

    monkeypatch.setattr(
        "sys.argv",
        [
            "run_folder_3mf_catalog_import.py",
            "--manifest",
            str(manifest_path),
            "--state",
            str(state_path),
            "--action",
            "dry-run",
        ],
    )

    assert runner_main() == 0
    payload = json.loads(capsys.readouterr().out)

    assert len(payload["dry_run"]["create_archive_upload"]) == 1
    assert payload["dry_run"]["attach_source_only"][0]["archive_id"] == 77


def test_run_catalog_import_inspect_returns_summary_without_manifest_write(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "SlicedReady.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    store = CatalogStateStore(state_path)
    record_id = manifest["candidates"][0]["record_id"]
    store.patch(record_id, {"disposition": "Keep", "import_plan": {"mode": "create_archive_upload"}})

    payload = run_catalog_import(manifest_path=manifest_path, state_path=state_path, action="inspect")

    assert payload["summary"]["counts"]["ready"] == 1
    assert payload["synthetic_manifest_path"] is None
    assert payload["dry_run"] is None


def test_folder_catalog_runner_run_backfill_writes_runner_state_and_provenance(tmp_path: Path, monkeypatch, capsys) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "SlicedReady.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest = build_manifest(source_root=source_root, include_patterns=["*.3mf"], exclude_patterns=[], recurse=True)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    state_path = tmp_path / "state" / "catalog_state.json"
    store = CatalogStateStore(state_path)
    record_id = manifest["candidates"][0]["record_id"]
    store.patch(record_id, {"disposition": "Keep", "import_plan": {"mode": "create_archive_upload", "provenance_tag_mode": "tags_and_notes"}})

    patched: dict[str, object] = {}

    def fake_run_backfill(synthetic_manifest_path, *, base_url, printer_id, api_key, backfill_action, allow_source_project_import, result_path):
        synthetic = json.loads(Path(synthetic_manifest_path).read_text(encoding="utf-8"))
        entry_id = synthetic["candidates"][0]["entry_id"]
        result = {"result": {"results": [{"entry_id": entry_id, "status": "uploaded_and_annotated", "created_archive_id": 501, "matched_archive_id": None}]}}
        result_path.write_text(json.dumps(result["result"], indent=2), encoding="utf-8")
        return result

    def fake_fetch_archive_detail(self, archive_id):
        return {"id": archive_id, "tags": "Hueforge", "notes": "Original user note"}

    def fake_patch_archive(self, archive_id, tags, notes):
        patched["archive_id"] = archive_id
        patched["tags"] = tags
        patched["notes"] = notes

    monkeypatch.setattr("tools.bambuddy.run_folder_3mf_catalog_import.run_backfill", fake_run_backfill)
    monkeypatch.setattr("tools.bambuddy.run_folder_3mf_catalog_import.BambuddyClient.fetch_archive_detail", fake_fetch_archive_detail)
    monkeypatch.setattr("tools.bambuddy.run_folder_3mf_catalog_import.BambuddyClient.patch_archive", fake_patch_archive)
    monkeypatch.setattr(
        "sys.argv",
        [
            "run_folder_3mf_catalog_import.py",
            "--manifest",
            str(manifest_path),
            "--state",
            str(state_path),
            "--action",
            "run-backfill",
            "--base-url",
            "http://bambuddy.local",
            "--printer-id",
            "1",
            "--write-back-results",
        ],
    )

    assert runner_main() == 0
    payload = json.loads(capsys.readouterr().out)
    updated = CatalogStateStore(state_path).get(record_id)

    assert payload["provenance_updates"][record_id]["status"] == "patched"
    assert patched["archive_id"] == 501
    assert "repair:recovered" in str(patched["tags"])
    assert "FOLDER_CATALOG_RECOVERY_V1" in str(patched["notes"])
    assert updated is not None
    assert updated["runner_state"]["created_archive_id"] == 501