from __future__ import annotations

import json
from pathlib import Path
from zipfile import ZipFile

from tools.bambuddy.build_synthetic_gcode_3mf import build_filaments_from_header, main as build_main


def test_synthetic_gcode_3mf_builder_creates_expected_package(tmp_path: Path, monkeypatch) -> None:
    gcode_path = tmp_path / "Recovered_plate_1.gcode"
    gcode_path.write_text(
        "; generated by Bambu Studio\n; estimated printing time = 1h 10m\n; filament_ids = GFA00;GFG02\n; filament_type = PLA;PETG\n; filament_colour = #F98C36;#68724D\nG1 X1 Y1 E1\n",
        encoding="utf-8",
    )
    output_path = tmp_path / "Recovered_plate_1.gcode.3mf"
    report_path = tmp_path / "report.json"
    monkeypatch.setattr(
        "sys.argv",
        [
            "build_synthetic_gcode_3mf.py",
            "--gcode",
            str(gcode_path),
            "--output",
            str(output_path),
            "--report",
            str(report_path),
        ],
    )

    result = build_main()

    assert result == 0
    assert output_path.exists()
    with ZipFile(output_path) as archive:
        names = set(archive.namelist())
        assert "Metadata/slice_info.config" in names
        assert "Metadata/project_settings.config" in names
        assert "Metadata/plate_1.gcode" in names
        assert "Metadata/plate_1.png" in names
        project_settings = json.loads(archive.read("Metadata/project_settings.config").decode("utf-8"))
        assert project_settings["filament_ids"] == ["GFA00", "GFG02"]
        assert project_settings["filament_type"] == ["PLA", "PETG"]
        assert project_settings["filament_colour"] == ["#F98C36", "#68724D"]


def test_build_filaments_from_header_uses_ids_types_and_colors() -> None:
    filaments = build_filaments_from_header(
        {
            "filament_slots": "GFA00;GFA01;GFSNL03;GFG02",
            "filament_types": "PLA;PLA;PLA;PETG",
            "filament_colours": "#F98C36;#68724D;#FFFFFF;#ABCDEF",
            "filament_weight_g": "1.5;2.5;3.5;4.5",
        }
    )

    assert [row["filament_id"] for row in filaments] == ["GFA00", "GFA01", "GFSNL03", "GFG02"]
    assert [row["type"] for row in filaments] == ["PLA", "PLA", "PLA", "PETG"]
    assert [row["color"] for row in filaments] == ["#F98C36", "#68724D", "#FFFFFF", "#ABCDEF"]
    assert [row["used_g"] for row in filaments] == [1.5, 2.5, 3.5, 4.5]


def test_synthetic_gcode_3mf_builder_reports_reference_differences(tmp_path: Path, monkeypatch) -> None:
    gcode_path = tmp_path / "Recovered_plate_1.gcode"
    gcode_path.write_text(
        "; generated by Bambu Studio\n; estimated printing time = 1h 10m\n; filament_ids = GFA00;GFG02\n; filament_type = PLA;PETG\n; filament_colour = #F98C36;#68724D\nG1 X1 Y1 E1\n",
        encoding="utf-8",
    )
    reference_path = tmp_path / "KnownGood.gcode.3mf"
    with ZipFile(reference_path, "w") as archive:
        archive.writestr("[Content_Types].xml", "<types />")
        archive.writestr("_rels/.rels", "<rels />")
        archive.writestr(
            "Metadata/slice_info.config",
            '<config><plate /><filament id="1" type="PLA" color="#F98C36" tray_info_idx="1" group_id="0" setting_id="GFA00" /><filament id="2" type="PETG" color="#68724D" tray_info_idx="2" group_id="0" setting_id="GFG02" /></config>',
        )
        archive.writestr(
            "Metadata/project_settings.config",
            json.dumps(
                {
                    "filament_ids": ["GFA00", "GFG02"],
                    "filament_type": ["PLA", "PETG"],
                    "filament_colour": ["#F98C36", "#68724D"],
                    "filament_colour_type": ["0", "0"],
                    "flush_volumes_matrix": "1,2,3,4",
                }
            ),
        )
        archive.writestr("Metadata/plate_1.gcode", "; generated by Bambu Studio\n")
        archive.writestr("Metadata/plate_1.png", b"png-bytes")
        archive.writestr("Metadata/extra_preview.png", b"png-bytes")
    output_path = tmp_path / "Recovered_plate_1.gcode.3mf"
    report_path = tmp_path / "report.json"
    monkeypatch.setattr(
        "sys.argv",
        [
            "build_synthetic_gcode_3mf.py",
            "--gcode",
            str(gcode_path),
            "--output",
            str(output_path),
            "--report",
            str(report_path),
            "--compare-to",
            str(reference_path),
        ],
    )

    build_main()

    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert report["comparisons"][0]["reference_path"] == str(reference_path)
    assert "Metadata/extra_preview.png" in report["comparisons"][0]["missing_from_generated"]
    assert report["comparisons"][0]["generated_project_settings_filaments"]["filament_ids"] == ["GFA00", "GFG02"]
    assert report["comparisons"][0]["missing_filament_project_settings_keys"] == ["flush_volumes_matrix"]

