from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from zipfile import ZipFile

from tools.bambuddy.gcode_forensics_viewer import (
    build_raw_wrap_checklist,
    build_effective_import_plan,
    build_path2_package_plan,
    build_runner_queue_preview,
    DecisionStore,
    inspect_local_artifact,
    load_json,
    search_local_source_candidates,
)


def _write_zip(path: Path, members: dict[str, str | bytes]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w") as archive:
        for name, content in members.items():
            archive.writestr(name, content)
    return path


def test_inspect_local_artifact_classifies_sliced_and_raw_gcode(tmp_path: Path) -> None:
    sliced_path = _write_zip(
        tmp_path / "SlicedProject.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
            "Metadata/plate_1.png": b"png-bytes",
        },
    )
    raw_gcode_path = tmp_path / "Recovered_plate_1.gcode"
    raw_gcode_path.write_text("; generated by Bambu Studio\n; filament used [g] = 12.34\nG1 X1 Y1 E1\n", encoding="utf-8")

    sliced = inspect_local_artifact(sliced_path, source_kind="linked_path")
    raw_gcode = inspect_local_artifact(raw_gcode_path, source_kind="linked_path")

    assert sliced["source_type"] == "bambu_studio_exported_sliced_3mf"
    assert sliced["canonical_archive_ready"] is True
    assert sliced["suggested_import_mode"] == "create_archive_upload"
    assert raw_gcode["source_type"] == "raw_gcode_file"
    assert raw_gcode["canonical_archive_ready"] is False
    assert raw_gcode["suggested_import_mode"] == "wrap_raw_gcode_experimental"
    assert raw_gcode["header_metadata"]["filament_weight_g"] == "12.34"


def test_decision_store_persists_source_queue_and_import_plan(tmp_path: Path) -> None:
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text('{"candidates": []}\n', encoding="utf-8")
    export_path = tmp_path / "decisions.json"
    store = DecisionStore(export_path, manifest_path, manifest_writeback=True)

    project_path = _write_zip(
        tmp_path / "ProjectSource.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    candidate = inspect_local_artifact(project_path, source_kind="linked_path")
    store.upsert_source_candidate("Example_plate_1.gcode", candidate, select=True)
    store.set_import_plan(
        "Example_plate_1.gcode",
        {
            "mode": "attach_source_only",
            "inferred_started_at": "2026-04-12T19:16:06Z",
            "override_started_at": "2026-04-12T19:20:00Z",
            "inferred_created_at": "2026-04-12T19:16:06Z",
            "notes": "Keep this tied to the recovered source project.",
            "missing_requirements": ["Need a sliced export before canonical archive upload."],
        },
    )

    payload = load_json(export_path)
    entry = payload["entries"][0]
    assert entry["gcode_name"] == "Example_plate_1.gcode"
    assert entry["selected_source_path"] == str(project_path)
    assert entry["source_files"][0]["source_type"] == "bambu_studio_source_3mf"
    assert entry["import_plan"]["mode"] == "attach_source_only"
    assert entry["import_plan"]["override_started_at"] == "2026-04-12T19:20:00Z"

    manifest = load_json(manifest_path)
    written = manifest["secondary_artifact_analysis"]["cache_secondary_artifacts"]["manual_triage_decisions"]["entries"][0]
    assert written["selected_source_path"] == str(project_path)
    assert written["import_plan"]["missing_requirements"] == ["Need a sliced export before canonical archive upload."]


def test_search_local_source_candidates_ranks_name_matches_first(tmp_path: Path) -> None:
    search_root = tmp_path / "sources"
    dragon = _write_zip(search_root / "Dragon.3mf", {"3D/Objects/object_1.model": "<model />"})
    _write_zip(search_root / "Unrelated.3mf", {"3D/Objects/object_1.model": "<model />"})

    record = {
        "gcode_name": "Dragon_plate_1.gcode",
        "prefix": "Dragon",
    }

    matches = search_local_source_candidates(record, [str(search_root)])

    assert matches
    assert matches[0]["path"] == str(dragon)
    assert matches[0]["match_score"] > 0
    assert matches[0]["source_kind"] == "search_match"


def test_search_local_source_candidates_keeps_adjacent_day_matches_within_time_window(tmp_path: Path) -> None:
    search_root = tmp_path / "sources"
    same_day = _write_zip(search_root / "CloseButDifferent.3mf", {"3D/Objects/object_1.model": "<model />"})
    prior_day = _write_zip(search_root / "NeighborDay.3mf", {"3D/Objects/object_1.model": "<model />"})

    same_day_ts = 1_712_974_800  # 2024-04-11T10:00:00Z
    prior_day_ts = same_day_ts - (23 * 3600)
    same_day.touch()
    prior_day.touch()
    import os

    os.utime(same_day, (same_day_ts, same_day_ts))
    os.utime(prior_day, (prior_day_ts, prior_day_ts))

    record = {
        "gcode_name": "CompletelyUnrelated_plate_1.gcode",
        "prefix": "TotallyDifferent",
        "last_write": datetime.fromtimestamp(same_day_ts - 1800, tz=timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
    }

    matches = search_local_source_candidates(record, [str(search_root)], horizon_hours=2)

    matched_paths = {row["path"] for row in matches}
    assert str(same_day) in matched_paths
    assert str(prior_day) in matched_paths
    same_day_row = next(row for row in matches if row["path"] == str(same_day))
    prior_day_row = next(row for row in matches if row["path"] == str(prior_day))
    assert same_day_row["within_search_horizon"] is True
    assert prior_day_row["day_relation"] == "previous_day"


def test_build_runner_queue_preview_matches_ready_status(tmp_path: Path) -> None:
    sliced_path = _write_zip(
        tmp_path / "Ready.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    selected_source = inspect_local_artifact(sliced_path, source_kind="linked_path")
    record = {
        "gcode_name": "Ready_plate_1.gcode",
        "last_write": "2026-04-12T19:16:06Z",
        "header_metadata": {},
        "decision": {
            "disposition": "Keep",
            "source_files": [selected_source],
            "selected_source_path": str(sliced_path),
            "import_plan": {
                "mode": "create_archive_upload",
                "inferred_started_at": "2026-04-12T19:16:06Z",
                "inferred_created_at": "2026-04-12T19:16:06Z",
            },
        },
    }

    preview = build_runner_queue_preview(record, build_effective_import_plan(record, selected_source), selected_source)

    assert preview["status"] == "ready"
    assert preview["selected_source_ready"] is True


def test_build_runner_queue_preview_marks_attach_source_as_manual(tmp_path: Path) -> None:
    source_project = _write_zip(
        tmp_path / "Source.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    selected_source = inspect_local_artifact(source_project, source_kind="linked_path")
    record = {
        "gcode_name": "Source_plate_1.gcode",
        "last_write": "2026-04-12T19:16:06Z",
        "header_metadata": {},
        "decision": {
            "disposition": "Keep",
            "archive_id": 170,
            "source_files": [selected_source],
            "selected_source_path": str(source_project),
            "import_plan": {
                "mode": "attach_source_only",
                "inferred_started_at": "2026-04-12T19:16:06Z",
                "inferred_created_at": "2026-04-12T19:16:06Z",
            },
        },
    }

    preview = build_runner_queue_preview(record, build_effective_import_plan(record, selected_source), selected_source)

    assert preview["status"] == "manual"
    assert "source-attachment step" in preview["reason"]


def test_build_raw_wrap_checklist_marks_missing_package_parts_for_raw_gcode(tmp_path: Path) -> None:
    raw_gcode_path = tmp_path / "Recovered_plate_1.gcode"
    raw_gcode_path.write_text(
        "; generated by Bambu Studio\n; estimated printing time = 1h 5m\n; filament_ids = 1;2\nG1 X1 Y1 E1\n",
        encoding="utf-8",
    )
    selected_source = inspect_local_artifact(raw_gcode_path, source_kind="linked_path")
    record = {
        "gcode_name": "Recovered_plate_1.gcode",
        "last_write": "2026-04-12T19:16:06Z",
        "header_metadata": selected_source["header_metadata"],
    }

    checklist = build_raw_wrap_checklist(record, selected_source)
    by_label = {item["label"]: item for item in checklist}

    assert by_label["Raw G-code Source"]["status"] == "present"
    assert by_label["Per-plate G-code Payload"]["status"] == "derivable"
    assert by_label["slice_info.config"]["status"] == "missing"
    assert by_label["AMS Mapping"]["status"] == "present"


def test_build_path2_package_plan_includes_reference_compare_targets(tmp_path: Path) -> None:
    backup_root = tmp_path / "backup"
    _write_zip(
        backup_root / "KnownGood_plate_1.gcode.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    raw_gcode_path = tmp_path / "Recovered_plate_1.gcode"
    raw_gcode_path.write_text(
        "; generated by Bambu Studio\n; estimated printing time = 1h 5m\nG1 X1 Y1 E1\n",
        encoding="utf-8",
    )
    selected_source = inspect_local_artifact(raw_gcode_path, source_kind="linked_path")
    record = {
        "gcode_name": "Recovered_plate_1.gcode",
        "last_write": "2026-04-12T19:16:06Z",
        "header_metadata": selected_source["header_metadata"],
        "decision": {
            "import_plan": {
                "mode": "wrap_raw_gcode_experimental",
                "inferred_started_at": "2026-04-12T19:16:06Z",
            }
        },
    }

    plan = build_path2_package_plan(record, selected_source, backup_root)

    assert plan["selected_source_path"] == str(raw_gcode_path)
    assert str((backup_root / "KnownGood_plate_1.gcode.3mf").resolve()) in plan["compare_to_references"]
    assert "--compare-to" in plan["command_preview"]


def test_build_path2_package_plan_carries_manual_override_fields(tmp_path: Path) -> None:
    backup_root = tmp_path / "backup"
    raw_gcode_path = tmp_path / "Recovered_plate_1.gcode"
    raw_gcode_path.write_text(
        "; generated by Bambu Studio\n; estimated printing time = 1h 5m\nG1 X1 Y1 E1\n",
        encoding="utf-8",
    )
    selected_source = inspect_local_artifact(raw_gcode_path, source_kind="linked_path")
    reference_path = tmp_path / "KnownGood.gcode.3mf"
    _write_zip(reference_path, {"Metadata/slice_info.config": "<slice-info />", "Metadata/plate_1.gcode": "; generated by Bambu Studio\n"})
    record = {
        "gcode_name": "Recovered_plate_1.gcode",
        "last_write": "2026-04-12T19:16:06Z",
        "header_metadata": selected_source["header_metadata"],
        "decision": {
            "import_plan": {
                "mode": "wrap_raw_gcode_experimental",
                "inferred_started_at": "2026-04-12T19:16:06Z",
                "path2_reference_template_path": str(reference_path),
                "path2_printer_model_id": "P1S",
                "path2_manual_filament_colours": "#111111;#222222",
                "path2_manual_filament_colour_types": "0;1",
                "path2_manual_filament_map": "1;1",
                "path2_manual_nozzle_diameter": "0.6",
            }
        },
    }

    plan = build_path2_package_plan(record, selected_source, backup_root)

    assert plan["reference_template_path"] == str(reference_path)
    assert plan["printer_model_id"] == "P1S"
    assert plan["manual_overrides"]["filament_colours"] == "#111111;#222222"
    assert "--reference-template" in plan["command_preview"]
    assert "--manual-filament-map" in plan["command_preview"]


def test_decision_store_dedupes_source_candidates_by_path(tmp_path: Path) -> None:
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text('{"candidates": []}\n', encoding="utf-8")
    export_path = tmp_path / "decisions.json"
    store = DecisionStore(export_path, manifest_path, manifest_writeback=False)
    project_path = _write_zip(
        tmp_path / "Duplicate.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    candidate = inspect_local_artifact(project_path, source_kind="search_match")
    store.upsert_source_candidate("Duplicate.gcode", candidate, select=True)
    store.upsert_source_candidate("Duplicate.gcode", dict(candidate), select=True)

    payload = load_json(export_path)
    assert len(payload["entries"][0]["source_files"]) == 1
