from __future__ import annotations

from pathlib import Path
from zipfile import ZipFile

from tools.bambuddy.gcode_forensics_viewer import (
    DecisionStore,
    inspect_local_artifact,
    load_json,
    search_local_source_candidates,
)


def _write_zip(path: Path, members: dict[str, str | bytes]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w") as archive:
        for name, content in members.items():
            archive.writestr(name, content)
    return path


def test_inspect_local_artifact_classifies_sliced_and_raw_gcode(tmp_path: Path) -> None:
    sliced_path = _write_zip(
        tmp_path / "SlicedProject.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
            "Metadata/plate_1.png": b"png-bytes",
        },
    )
    raw_gcode_path = tmp_path / "Recovered_plate_1.gcode"
    raw_gcode_path.write_text("; generated by Bambu Studio\n; filament used [g] = 12.34\nG1 X1 Y1 E1\n", encoding="utf-8")

    sliced = inspect_local_artifact(sliced_path, source_kind="linked_path")
    raw_gcode = inspect_local_artifact(raw_gcode_path, source_kind="linked_path")

    assert sliced["source_type"] == "bambu_studio_exported_sliced_3mf"
    assert sliced["canonical_archive_ready"] is True
    assert sliced["suggested_import_mode"] == "create_archive_upload"
    assert raw_gcode["source_type"] == "raw_gcode_file"
    assert raw_gcode["canonical_archive_ready"] is False
    assert raw_gcode["suggested_import_mode"] == "wrap_raw_gcode_experimental"
    assert raw_gcode["header_metadata"]["filament_weight_g"] == "12.34"


def test_decision_store_persists_source_queue_and_import_plan(tmp_path: Path) -> None:
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text('{"candidates": []}\n', encoding="utf-8")
    export_path = tmp_path / "decisions.json"
    store = DecisionStore(export_path, manifest_path, manifest_writeback=True)

    project_path = _write_zip(
        tmp_path / "ProjectSource.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    candidate = inspect_local_artifact(project_path, source_kind="linked_path")
    store.upsert_source_candidate("Example_plate_1.gcode", candidate, select=True)
    store.set_import_plan(
        "Example_plate_1.gcode",
        {
            "mode": "attach_source_only",
            "inferred_started_at": "2026-04-12T19:16:06Z",
            "override_started_at": "2026-04-12T19:20:00Z",
            "inferred_created_at": "2026-04-12T19:16:06Z",
            "notes": "Keep this tied to the recovered source project.",
            "missing_requirements": ["Need a sliced export before canonical archive upload."],
        },
    )

    payload = load_json(export_path)
    entry = payload["entries"][0]
    assert entry["gcode_name"] == "Example_plate_1.gcode"
    assert entry["selected_source_path"] == str(project_path)
    assert entry["source_files"][0]["source_type"] == "bambu_studio_source_3mf"
    assert entry["import_plan"]["mode"] == "attach_source_only"
    assert entry["import_plan"]["override_started_at"] == "2026-04-12T19:20:00Z"

    manifest = load_json(manifest_path)
    written = manifest["secondary_artifact_analysis"]["cache_secondary_artifacts"]["manual_triage_decisions"]["entries"][0]
    assert written["selected_source_path"] == str(project_path)
    assert written["import_plan"]["missing_requirements"] == ["Need a sliced export before canonical archive upload."]


def test_search_local_source_candidates_ranks_name_matches_first(tmp_path: Path) -> None:
    search_root = tmp_path / "sources"
    dragon = _write_zip(search_root / "Dragon.3mf", {"3D/Objects/object_1.model": "<model />"})
    _write_zip(search_root / "Unrelated.3mf", {"3D/Objects/object_1.model": "<model />"})

    record = {
        "gcode_name": "Dragon_plate_1.gcode",
        "prefix": "Dragon",
    }

    matches = search_local_source_candidates(record, [str(search_root)])

    assert matches
    assert matches[0]["path"] == str(dragon)
    assert matches[0]["match_score"] > 0
    assert matches[0]["source_kind"] == "search_match"


def test_decision_store_dedupes_source_candidates_by_path(tmp_path: Path) -> None:
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text('{"candidates": []}\n', encoding="utf-8")
    export_path = tmp_path / "decisions.json"
    store = DecisionStore(export_path, manifest_path, manifest_writeback=False)
    project_path = _write_zip(
        tmp_path / "Duplicate.3mf",
        {
            "3D/Objects/object_1.model": "<model />",
        },
    )
    candidate = inspect_local_artifact(project_path, source_kind="search_match")
    store.upsert_source_candidate("Duplicate.gcode", candidate, select=True)
    store.upsert_source_candidate("Duplicate.gcode", dict(candidate), select=True)

    payload = load_json(export_path)
    assert len(payload["entries"][0]["source_files"]) == 1
