from __future__ import annotations

import json
from pathlib import Path
from zipfile import ZipFile

import pytest

from tools.bambuddy.generate_folder_3mf_catalog import (
    build_manifest,
    is_probably_offline_onedrive,
    is_windows_cloud_reparse_tag,
    main as generate_main,
)


def _write_zip(path: Path, members: dict[str, str | bytes]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w") as archive:
        for name, content in members.items():
            archive.writestr(name, content)
    return path


def test_build_manifest_catalogs_candidates_and_support_files(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    model_path = _write_zip(
        source_root / "Projects" / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
            "Metadata/plate_1.png": b"png-bytes",
        },
    )
    (model_path.parent / "Widget.gcode").write_text("G1 X1 Y1 E1\n", encoding="utf-8")
    (model_path.parent / "Widget.txt").write_text("printed on machine A\n", encoding="utf-8")

    manifest = build_manifest(
        source_root=source_root,
        include_patterns=["*.3mf"],
        exclude_patterns=[],
        recurse=True,
    )

    assert manifest["workflow"] == "folder_3mf_catalog"
    assert manifest["summary"]["candidate_count"] == 1
    candidate = manifest["candidates"][0]
    assert candidate["primary_artifact_kind"] == "sliced_3mf"
    assert candidate["canonical_archive_ready"] is True
    assert candidate["best_inferred_print_time_source"] == "filesystem:saved_timestamp"
    support_paths = {row["relative_path"] for row in candidate["supporting_files"]}
    assert "projects/widget.gcode" in support_paths
    assert "projects/widget.txt" in support_paths


def test_build_manifest_preserves_missing_candidates_from_previous_manifest(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    model_path = _write_zip(
        source_root / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    previous_manifest = build_manifest(
        source_root=source_root,
        include_patterns=["*.3mf"],
        exclude_patterns=[],
        recurse=True,
    )
    model_path.unlink()

    refreshed = build_manifest(
        source_root=source_root,
        include_patterns=["*.3mf"],
        exclude_patterns=[],
        recurse=True,
        previous_manifest=previous_manifest,
    )

    assert refreshed["summary"]["candidate_count"] == 1
    candidate = refreshed["candidates"][0]
    assert candidate["file_status"] == "missing_on_rescan"
    assert candidate["missing_detected_at"] is not None
    assert "file no longer exists on latest rescan" in candidate["availability_notes"]
    assert candidate["source_path"].endswith("Widget.3mf")


def test_main_rejects_output_inside_selected_source_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source_root = tmp_path / "source"
    _write_zip(
        source_root / "Widget.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    output_path = source_root / "manifest.json"
    monkeypatch.setattr(
        "sys.argv",
        [
            "generate_folder_3mf_catalog.py",
            "--source-root",
            str(source_root),
            "--output",
            str(output_path),
        ],
    )

    with pytest.raises(ValueError, match="outside the selected source root"):
        generate_main()

    assert not output_path.exists()


def test_is_probably_offline_onedrive_detects_offline_file_attributes() -> None:
    offline_attributes = 0x00001000 | 0x00100000
    pinned_attributes = 0x00080000

    assert is_probably_offline_onedrive(offline_attributes) is True
    assert is_probably_offline_onedrive(pinned_attributes) is False


def test_is_probably_offline_onedrive_detects_cloud_reparse_placeholders() -> None:
    unpinned_attributes = 0x00100000
    cloud_reparse_tag = 0x9000001A

    assert is_windows_cloud_reparse_tag(cloud_reparse_tag) is True
    assert is_probably_offline_onedrive(unpinned_attributes, cloud_reparse_tag) is True