import json
from __future__ import annotations

from pathlib import Path
from zipfile import ZipFile
from urllib.request import Request

from tools.bambuddy.run_forensics_import_queue import (
    assess_entry,
    main as runner_main,
    build_synthetic_candidate,
    build_synthetic_manifest,
    build_multipart_payload,
    queue_summary,
    read_manifest_triage_entries,
    upload_source_attachment,
    update_source_manifest,
)
from tools.bambuddy.gcode_forensics_viewer import write_json, load_json


def _write_zip(path: Path, members: dict[str, str | bytes]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w") as archive:
        for name, content in members.items():
            archive.writestr(name, content)
    return path


def _write_manifest(path: Path, entry: dict[str, object]) -> Path:
    payload = {
        "candidates": [],
        "secondary_artifact_analysis": {
            "cache_secondary_artifacts": {
                "manual_triage_decisions": {
                    "entries": [entry]
                }
            }
        },
    }
    write_json(path, payload)
    return path


def test_runner_assess_entry_marks_sliced_keep_item_ready(tmp_path: Path) -> None:
    source_path = _write_zip(
        tmp_path / "Dragon.gcode.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    entry = {
        "gcode_name": "Dragon_plate_1.gcode",
        "disposition": "Keep",
        "selected_source_path": str(source_path),
        "source_files": [
            {
                "path": str(source_path),
                "source_type": "bambu_studio_exported_sliced_3mf",
                "canonical_archive_ready": True,
                "suggested_import_mode": "create_archive_upload",
                "modified_at": "2026-04-12T19:16:06Z",
            }
        ],
        "import_plan": {
            "mode": "create_archive_upload",
            "inferred_started_at": "2026-04-12T19:16:06Z",
            "inferred_created_at": "2026-04-12T19:16:06Z",
        },
    }

    item = assess_entry(entry)

    assert item.status == "ready"
    assert item.mode == "create_archive_upload"
    assert item.started_at == "2026-04-12T19:16:06Z"

    candidate = build_synthetic_candidate(item)
    assert candidate["source_type"] == "bambu_studio_exported_sliced_3mf"
    assert candidate["timestamp_evidence"]["timestamp_candidates"][0]["source"] == "forensics:started_at"


def test_runner_assess_entry_blocks_raw_gcode_wrap_path(tmp_path: Path) -> None:
    source_path = tmp_path / "Recovered_plate_1.gcode"
    source_path.write_text("; generated by Bambu Studio\n", encoding="utf-8")
    entry = {
        "gcode_name": "Recovered_plate_1.gcode",
        "disposition": "Keep",
        "selected_source_path": str(source_path),
        "source_files": [
            {
                "path": str(source_path),
                "source_type": "raw_gcode_file",
                "canonical_archive_ready": False,
                "suggested_import_mode": "wrap_raw_gcode_experimental",
                "modified_at": "2026-04-11T19:16:06Z",
                "header_metadata": {"filament_slots": "0"},
            }
        ],
        "import_plan": {
            "mode": "wrap_raw_gcode_experimental",
            "inferred_started_at": "2026-04-11T19:16:06Z",
        },
    }

    item = assess_entry(entry)

    assert item.status == "blocked"
    assert any("filament slot-to-type/color mapping" in row for row in item.missing_requirements)


def test_runner_can_read_writeback_and_update_manifest_results(tmp_path: Path) -> None:
    source_path = _write_zip(
        tmp_path / "Bat.gcode.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
        },
    )
    manifest_path = _write_manifest(
        tmp_path / "manifest.json",
        {
            "gcode_name": "Bat_plate_1.gcode",
            "disposition": "Keep",
            "selected_source_path": str(source_path),
            "source_files": [
                {
                    "path": str(source_path),
                    "source_type": "bambu_studio_exported_sliced_3mf",
                    "canonical_archive_ready": True,
                    "suggested_import_mode": "create_archive_upload",
                    "modified_at": "2026-04-12T19:16:06Z",
                }
            ],
            "import_plan": {
                "mode": "create_archive_upload",
                "inferred_started_at": "2026-04-12T19:16:06Z",
                "inferred_created_at": "2026-04-12T19:16:06Z",
            },
        },
    )

    entries = read_manifest_triage_entries(manifest_path)
    assert len(entries) == 1
    item = assess_entry(entries[0])
    synthetic = build_synthetic_manifest([item], batch_id="forensics-test")
    synthetic_manifest_path = tmp_path / "synthetic.json"
    write_json(synthetic_manifest_path, synthetic)

    synthetic_entry = synthetic["candidates"][0]
    backfill_result = {
        "result": {
            "results": [
                {
                    "entry_id": synthetic_entry["entry_id"],
                    "status": "uploaded_and_annotated",
                    "reason": "Archive created from manifest candidate.",
                    "created_archive_id": 612,
                    "matched_archive_id": None,
                }
            ]
        },
        "result_path": str(tmp_path / "result.json"),
    }
    update_source_manifest(
        manifest_path,
        [item],
        synthetic_manifest_path=synthetic_manifest_path,
        backfill_result=backfill_result,
        repair_results={"Bat_plate_1.gcode": {"applied": True}},
    )

    updated = load_json(manifest_path)
    runner = updated["secondary_artifact_analysis"]["cache_secondary_artifacts"]["manual_triage_decisions"]["entries"][0]["import_runner"]
    assert runner["queue_status"] == "ready"
    assert runner["created_archive_id"] == 612
    assert runner["runtime_repair"]["applied"] is True

    summary = queue_summary([item])
    assert summary["counts"]["ready"] == 1


def test_build_multipart_payload_contains_file_boundary() -> None:
    body, boundary = build_multipart_payload(
        files=[{"field_name": "file", "filename": "Source.3mf", "content": b"abc", "content_type": "application/octet-stream"}]
    )

    assert boundary.encode("utf-8") in body
    assert b'filename="Source.3mf"' in body
    assert b"abc" in body


def test_upload_source_attachment_posts_to_archive_source_endpoint(tmp_path: Path, monkeypatch) -> None:
    source_path = _write_zip(tmp_path / "Source.3mf", {"3D/Objects/object_1.model": "<model />"})
    captured: dict[str, object] = {}

    class DummyResponse:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, tb):
            return False

        def read(self):
            return json.dumps({"status": "uploaded", "source_3mf_path": "archive/1/source/Source.3mf", "filename": "Source.3mf"}).encode("utf-8")

    def fake_urlopen(request: Request):
        captured["url"] = request.full_url
        captured["content_type"] = request.headers.get("Content-type") or request.headers.get("Content-Type")
        captured["api_key"] = request.headers.get("X-api-key") or request.headers.get("X-API-Key")
        captured["body"] = request.data
        return DummyResponse()

    monkeypatch.setattr("urllib.request.urlopen", fake_urlopen)

    result = upload_source_attachment(170, source_path, base_url="http://bambuddy.socko.us", api_key="secret")

    assert captured["url"] == "http://bambuddy.socko.us/api/v1/archives/170/source"
    assert "multipart/form-data" in str(captured["content_type"])
    assert captured["api_key"] == "secret"
    assert b"Source.3mf" in bytes(captured["body"])
    assert result["status"] == "uploaded"


def test_runner_dry_run_generates_path2_artifact_and_attachment_preview(tmp_path: Path, monkeypatch, capsys) -> None:
    raw_gcode_path = tmp_path / "Recovered_plate_1.gcode"
    raw_gcode_path.write_text(
        "; generated by Bambu Studio\n; estimated printing time = 1h 10m\n; filament_ids = 1;2\nG1 X1 Y1 E1\n",
        encoding="utf-8",
    )
    source_project = _write_zip(tmp_path / "Source.3mf", {"3D/Objects/object_1.model": "<model />"})
    reference = _write_zip(
        tmp_path / "KnownGood.gcode.3mf",
        {
            "Metadata/slice_info.config": "<slice-info />",
            "Metadata/project_settings.config": "{}",
            "Metadata/plate_1.gcode": "; generated by Bambu Studio\n",
            "Metadata/plate_1.png": b"png-bytes",
        },
    )
    manifest_path = _write_manifest(
        tmp_path / "manifest.json",
        {
            "gcode_name": "Recovered_plate_1.gcode",
            "disposition": "Keep",
            "archive_id": 170,
            "selected_source_path": str(raw_gcode_path),
            "source_files": [
                {
                    "path": str(raw_gcode_path),
                    "source_type": "raw_gcode_file",
                    "canonical_archive_ready": False,
                    "suggested_import_mode": "wrap_raw_gcode_experimental",
                    "modified_at": "2026-04-11T19:16:06Z",
                    "header_metadata": {"filament_slots": "1;2", "print_time": "1h 10m"},
                },
                {
                    "path": str(source_project),
                    "source_type": "bambu_studio_source_3mf",
                    "canonical_archive_ready": False,
                    "suggested_import_mode": "attach_source_only",
                    "modified_at": "2026-04-11T19:16:06Z",
                },
            ],
            "import_plan": {
                "mode": "wrap_raw_gcode_experimental",
                "inferred_started_at": "2026-04-11T19:16:06Z",
            },
        },
    )
    manifest = load_json(manifest_path)
    manifest["secondary_artifact_analysis"]["cache_secondary_artifacts"]["manual_triage_decisions"]["entries"].append(
        {
            "gcode_name": "Source_plate_1.gcode",
            "disposition": "Keep",
            "archive_id": 171,
            "selected_source_path": str(source_project),
            "source_files": [
                {
                    "path": str(source_project),
                    "source_type": "bambu_studio_source_3mf",
                    "canonical_archive_ready": False,
                    "suggested_import_mode": "attach_source_only",
                    "modified_at": "2026-04-12T19:16:06Z",
                }
            ],
            "import_plan": {
                "mode": "attach_source_only",
                "inferred_started_at": "2026-04-12T19:16:06Z",
            },
        }
    )
    write_json(manifest_path, manifest)
    dry_run_dir = tmp_path / "dry-run"
    monkeypatch.setattr(
        "sys.argv",
        [
            "run_forensics_import_queue.py",
            "--manifest",
            str(manifest_path),
            "--action",
            "dry-run",
            "--dry-run-output-dir",
            str(dry_run_dir),
            "--compare-to",
            str(reference),
        ],
    )

    result = runner_main()
    payload = json.loads(capsys.readouterr().out)

    assert result == 0
    assert payload["dry_run"]["source_attachments"]["Source_plate_1.gcode"]["would_call"].endswith("/171/source")
    artifact = payload["dry_run"]["path2_artifacts"]["Recovered_plate_1.gcode"]
    assert Path(artifact["output_path"]).exists()
    assert artifact["report"]["comparisons"][0]["reference_path"] == str(reference)