#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


GENERIC_MULTI_PLATE_PREFIXES = {
    "0",
    "Split over more plates part count_plate below 64",
    "Big printer - 0",
    "Oversized Gang Plates_ 0",
    "Wide Rounded - 0",
    "AMS Rack",
}

PAIRING_WINDOW_SECONDS = 120
SAMPLE_LIMIT = 5
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze raw cache gcode/image secondary artifacts for a backfill manifest.")
    parser.add_argument("--source-root", required=True, help="Root of the SD-card backup")
    parser.add_argument("--manifest", required=True, help="Backfill manifest JSON path")
    parser.add_argument("--pairings-output", required=True, help="Output JSON path for gcode pairing rows")
    parser.add_argument("--write-manifest", action="store_true", help="Write summary analysis back into the manifest")
    return parser.parse_args()


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8-sig") as handle:
        return json.load(handle)


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


def iso_utc_from_timestamp(timestamp: float) -> str:
    return datetime.fromtimestamp(timestamp, tz=UTC).isoformat().replace("+00:00", "Z")


def parse_iso_timestamp(value: str | None) -> datetime | None:
    if not value:
        return None
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(UTC)


def normalize_name(value: str) -> str:
    lowered = value.lower().replace("&quot;", '"')
    lowered = lowered.replace("_", " ")
    lowered = re.sub(r"\.stl$", "", lowered)
    lowered = re.sub(r"\.gcode$", "", lowered)
    lowered = re.sub(r"\.3mf$", "", lowered)
    lowered = re.sub(r"\s+", " ", lowered)
    return lowered.strip()


def gcode_prefix(name: str) -> str:
    match = re.match(r"(?P<prefix>.+?)_plate_\d+\.gcode$", name, flags=re.IGNORECASE)
    if match:
        return match.group("prefix")
    return Path(name).stem


def parse_gcode_header(gcode_path: Path) -> dict[str, str]:
    patterns = {
        "slicer": re.compile(r"generated by (?P<value>.+)", re.IGNORECASE),
        "print_time": re.compile(r"estimated printing time(?: \(normal mode\))?\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "total_layers": re.compile(r"total layer number\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "filament_weight_g": re.compile(r"filament used \[g\]\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "max_z_height": re.compile(r"max_z_height\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "filament_slots": re.compile(r"filament_ids\s*=\s*(?P<value>.+)", re.IGNORECASE),
    }
    extracted: dict[str, str] = {}
    with gcode_path.open("r", encoding="utf-8", errors="ignore") as handle:
        for index, raw_line in enumerate(handle):
            if index > 350:
                break
            line = raw_line.strip().lstrip("; ")
            for key, pattern in patterns.items():
                if key in extracted:
                    continue
                match = pattern.search(line)
                if match:
                    extracted[key] = match.group("value").strip()
    return extracted


def build_candidate_index(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for candidate in manifest.get("candidates", []):
        relative_path = str(candidate.get("relative_path") or "").replace("\\", "/")
        filename = Path(relative_path).name
        stem = Path(filename).stem
        entries.append(
            {
                "relative_path": relative_path,
                "stem": stem,
                "normalized_stem": normalize_name(stem),
                "last_write": parse_iso_timestamp(candidate.get("last_write_time")),
                "processing_bucket": candidate.get("processing_bucket"),
                "import_status": candidate.get("import_status"),
                "archive_id": candidate.get("created_archive_id") or candidate.get("matched_archive_id"),
            }
        )
    return entries


def analyze(source_root: Path, manifest: dict[str, Any]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    cache_dir = source_root / "cache"
    image_dir = source_root / "image"
    image_md5_dir = image_dir / "md5"
    model_dir = source_root / "model"

    cache_files = list(cache_dir.iterdir()) if cache_dir.exists() else []
    gcode_files = sorted(path for path in cache_files if path.is_file() and path.suffix.lower() == ".gcode")
    three_mf_files = sorted(path for path in cache_files if path.is_file() and path.suffix.lower() == ".3mf")
    bbl_files = sorted(path for path in cache_files if path.is_file() and path.suffix.lower() == ".bbl")
    image_files = (
        sorted(path for path in image_dir.iterdir() if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES)
        if image_dir.exists()
        else []
    )
    image_md5_files = sorted(path for path in image_md5_dir.iterdir() if path.is_file() and path.suffix.lower() == ".md5") if image_md5_dir.exists() else []
    model_gcode_files = sorted(path for path in model_dir.iterdir() if path.is_file() and path.suffix.lower() == ".gcode") if model_dir.exists() else []

    candidate_index = build_candidate_index(manifest)
    exact_match_count = 0
    near_time_only_count = 0
    ambiguous_rows: list[dict[str, Any]] = []
    grouped_ambiguous: dict[str, list[dict[str, Any]]] = defaultdict(list)
    image_candidate_matches = 0
    image_ambiguous_matches = 0
    pairings: list[dict[str, Any]] = []

    image_inventory = [
        {
            "name": image_path.name,
            "last_write": datetime.fromtimestamp(image_path.stat().st_mtime, tz=UTC),
        }
        for image_path in image_files
    ]

    for gcode_path in gcode_files:
        prefix = gcode_prefix(gcode_path.name)
        normalized_prefix = normalize_name(prefix)
        stat = gcode_path.stat()
        last_write = datetime.fromtimestamp(stat.st_mtime, tz=UTC)

        exact_matches = [
            entry["relative_path"]
            for entry in candidate_index
            if entry["normalized_stem"] == normalized_prefix
        ]

        near_time_matches = []
        if not exact_matches:
            for entry in candidate_index:
                candidate_time = entry["last_write"]
                if candidate_time is None:
                    continue
                delta_seconds = abs((candidate_time - last_write).total_seconds())
                if delta_seconds <= PAIRING_WINDOW_SECONDS:
                    near_time_matches.append(entry["relative_path"])

        nearby_images = [
            image["name"]
            for image in image_inventory
            if abs((image["last_write"] - last_write).total_seconds()) <= PAIRING_WINDOW_SECONDS
        ]

        row = {
            "gcode": gcode_path.name,
            "prefix": prefix,
            "size": stat.st_size,
            "last_write": last_write.isoformat().replace("+00:00", "Z"),
            "exact_3mf_matches": exact_matches,
            "near_time_3mf_matches": near_time_matches,
            "nearby_images": nearby_images,
        }
        pairings.append(row)

        if exact_matches:
            exact_match_count += 1
        elif near_time_matches:
            near_time_only_count += 1
        else:
            header = parse_gcode_header(gcode_path)
            ambiguous_row = row | {"header": header}
            ambiguous_rows.append(ambiguous_row)
            grouped_ambiguous[prefix].append(ambiguous_row)

        if nearby_images:
            if exact_matches or near_time_matches:
                image_candidate_matches += 1
            else:
                image_ambiguous_matches += 1

    ambiguous_count = len(ambiguous_rows)
    generic_ambiguous = [row for row in ambiguous_rows if row["prefix"] in GENERIC_MULTI_PLATE_PREFIXES]
    named_ambiguous = [row for row in ambiguous_rows if row["prefix"] not in GENERIC_MULTI_PLATE_PREFIXES]

    top_groups = []
    for prefix, rows in sorted(grouped_ambiguous.items(), key=lambda item: (-len(item[1]), item[0])):
        if prefix not in GENERIC_MULTI_PLATE_PREFIXES:
            continue
        timestamps = [parse_iso_timestamp(row["last_write"]) for row in rows]
        timestamps = [value for value in timestamps if value is not None]
        top_groups.append(
            {
                "prefix": prefix,
                "count": len(rows),
                "sample_gcodes": [row["gcode"] for row in rows[:SAMPLE_LIMIT]],
                "last_write_min": min(timestamps).isoformat().replace("+00:00", "Z") if timestamps else None,
                "last_write_max": max(timestamps).isoformat().replace("+00:00", "Z") if timestamps else None,
                "sample_header": rows[0].get("header", {}),
            }
        )

    single_examples = [
        {
            "gcode": row["gcode"],
            "prefix": row["prefix"],
            "last_write": row["last_write"],
            "size": row["size"],
            "header": row.get("header", {}),
        }
        for row in named_ambiguous[:6]
    ]

    image_match_examples = []
    for image in image_inventory:
        candidate_matches = [
            entry["relative_path"]
            for entry in candidate_index
            if entry["last_write"] is not None and abs((entry["last_write"] - image["last_write"]).total_seconds()) <= PAIRING_WINDOW_SECONDS
        ]
        if candidate_matches:
            image_match_examples.append(
                {
                    "image": image["name"],
                    "image_last_write": image["last_write"].isoformat().replace("+00:00", "Z"),
                    "sample_candidates": candidate_matches[:3],
                }
            )
        if len(image_match_examples) >= 6:
            break

    summary = {
        "generated_at": datetime.now(tz=UTC).isoformat().replace("+00:00", "Z"),
        "archive_upload_contract": {
            "manual_archive_upload_accepts": ".3mf only",
            "raw_gcode_supported_as_archive_input": False,
            "notes": [
                "Current Bambuddy archive upload route rejects non-.3mf inputs.",
                "Raw cache .gcode files may still carry useful header metadata for manual recovery analysis.",
                "The current manifest state machine does not represent raw .gcode or .bbl files as import candidates.",
            ],
        },
        "cache_secondary_artifacts": {
            "total_non_3mf": len(gcode_files) + len(bbl_files),
            "gcode_count": len(gcode_files),
            "bbl_count": len(bbl_files),
            "gcode_exact_3mf_match_count": exact_match_count,
            "gcode_near_time_only_count": near_time_only_count,
            "gcode_ambiguous_count": ambiguous_count,
            "interpretation": "Most raw cache gcode files look like execution-side secondary artifacts. The ambiguous remainder should be treated as manual forensic follow-up, not automatic archive inputs.",
            "ambiguous_top_groups": top_groups,
            "ambiguous_single_examples": single_examples,
            "recovery_buckets": [
                {
                    "bucket": "likely_secondary_to_represented_3mf",
                    "count": exact_match_count + near_time_only_count,
                    "criteria": "Raw cache gcode has either an exact stem match to a cache 3mf or a near-time-only cache 3mf match.",
                    "recommended_action": "Use the related 3mf candidate or existing archive row as the canonical representation instead of treating the gcode as a missing archive input.",
                },
                {
                    "bucket": "ambiguous_generic_multi_plate_groups",
                    "count": len(generic_ambiguous),
                    "criteria": "Ambiguous gcode falls into one of the repeated generic prefixes used by grouped plate artifacts.",
                    "recommended_action": "Review as grouped plate sets first rather than as standalone missing projects.",
                },
                {
                    "bucket": "ambiguous_named_singletons_or_small_groups",
                    "count": len(named_ambiguous),
                    "criteria": "Ambiguous gcode has no 3mf match and is not part of the large generic multi-plate groups.",
                    "recommended_action": "Treat as the highest-value manual-review bucket for possible missed historical prints.",
                },
            ],
        },
        "image_analysis": {
            "image_png_count": len([path for path in image_files if path.suffix.lower() == ".png"]),
            "image_jpg_count": len([path for path in image_files if path.suffix.lower() in {".jpg", ".jpeg"}]),
            "image_file_count": len(image_files),
            "image_md5_count": len(image_md5_files),
            "md5_sidecar_shape": "Each image/png may have a same-basename image/md5/*.md5 sidecar containing a single hash.",
            "images_with_cache_candidate_within_2m": image_candidate_matches,
            "images_with_ambiguous_gcode_within_2m": image_ambiguous_matches,
            "candidate_match_examples": image_match_examples,
            "notes": [
                "Image timestamps are supporting evidence only, not canonical archive inputs.",
                "A high image count without matching 3mf files is consistent with the printer preserving snapshots separately from execution artifacts.",
            ],
        },
        "model_gcode_inventory": {
            "model_gcode_count": len(model_gcode_files),
            "sample_files": [path.name for path in model_gcode_files[:SAMPLE_LIMIT]],
            "notes": [
                "The model directory contains printer-supplied or model-library gcode files, not historical cache 3mf bundles.",
                "This supports the conclusion that the backup captured multiple printer-side storage classes, not just archive-ready 3mf inputs.",
            ],
        },
        "storage_interpretation": {
            "observed_cache_three_mf_count": len(three_mf_files),
            "observed_cache_gcode_count": len(gcode_files),
            "observed_model_gcode_count": len(model_gcode_files),
            "conclusion": "This older backup appears dominated by printer execution artifacts (.gcode) plus a small set of archive-grade cached .3mf bundles. That does not by itself prove a global Bambu storage-format change; it is more consistent with a different retention mix or capture point in the printer cache lifecycle.",
            "notes": [
                "Many cache gcode filenames are plate-specific (`*_plate_N.gcode`), which points to execution-side job artifacts rather than canonical archive packages.",
                "Only 20 cache .3mf files are present, but those 20 all behaved like valid historical archive inputs during import.",
                "The separate model directory also contains gcode-only assets, which suggests the printer stores multiple categories of printable artifacts outside the archive-grade cache bundles.",
            ],
        },
    }

    return pairings, summary


def main() -> int:
    args = parse_args()
    source_root = Path(args.source_root)
    manifest_path = Path(args.manifest)
    pairings_output = Path(args.pairings_output)

    manifest = load_json(manifest_path)
    pairings, summary = analyze(source_root, manifest)
    write_json(pairings_output, pairings)

    if args.write_manifest:
        manifest["secondary_artifact_analysis"] = summary
        write_json(manifest_path, manifest)

    print(json.dumps({
        "pairings_output": str(pairings_output),
        "manifest_updated": bool(args.write_manifest),
        "gcode_rows": len(pairings),
        "secondary_artifact_analysis_generated_at": summary["generated_at"],
        "gcode_count": summary["cache_secondary_artifacts"]["gcode_count"],
        "bbl_count": summary["cache_secondary_artifacts"]["bbl_count"],
        "gcode_exact_3mf_match_count": summary["cache_secondary_artifacts"]["gcode_exact_3mf_match_count"],
        "gcode_near_time_only_count": summary["cache_secondary_artifacts"]["gcode_near_time_only_count"],
        "gcode_ambiguous_count": summary["cache_secondary_artifacts"]["gcode_ambiguous_count"],
        "image_png_count": summary["image_analysis"]["image_png_count"],
        "model_gcode_count": summary["model_gcode_inventory"]["model_gcode_count"],
    }, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())