from __future__ import annotations

import argparse
import functools
import html
import json
import mimetypes
import re
import webbrowser
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, quote, urlencode, urlparse


GENERIC_MULTI_PLATE_PREFIXES = {
    "0",
    "Split over more plates part count_plate below 64",
    "Big printer - 0",
    "Oversized Gang Plates_ 0",
    "Wide Rounded - 0",
    "AMS Rack",
}

DISPOSITIONS = ["Keep", "Ignore", "Investigate"]

SVG_PALETTE = [
    "#006d77",
    "#e76f51",
    "#2a9d8f",
    "#ffb703",
    "#8d99ae",
    "#457b9d",
    "#6a4c93",
    "#ef476f",
]

GCODE_PREVIEW_MODULE_URL = "https://esm.sh/gcode-preview@2.18.0?bundle"


def load_json(path: Path):
    with path.open("r", encoding="utf-8-sig") as handle:
        return json.load(handle)


def write_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def parse_timestamp(value: str | None) -> datetime | None:
    if not value:
        return None
    normalized = value.replace("Z", "+00:00")
    parsed = datetime.fromisoformat(normalized)
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def normalize_match_values(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        stripped = value.strip()
        return [stripped] if stripped else []
    if isinstance(value, list):
        results: list[str] = []
        for item in value:
            results.extend(normalize_match_values(item))
        return results
    if isinstance(value, dict):
        return []
    text = str(value).strip()
    return [text] if text else []


def normalize_cache_relative_path(name: str) -> str:
    normalized = name.replace("\\", "/")
    if "/" in normalized:
        return normalized
    return f"cache/{normalized}"


def normalize_disposition(value: str | None) -> str | None:
    if not value:
        return None
    value = value.strip().title()
    return value if value in DISPOSITIONS else None


def human_size(size_bytes: int) -> str:
    if size_bytes < 1024:
        return f"{size_bytes} B"
    units = ["KB", "MB", "GB"]
    value = float(size_bytes)
    for unit in units:
        value /= 1024.0
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f} {unit}"
    return f"{size_bytes} B"


def escape_json_for_html(value) -> str:
    return html.escape(json.dumps(value, indent=2, ensure_ascii=False))


def parse_archive_id(value: str | int | None) -> int | None:
    if value in (None, ""):
        return None
    return int(str(value).strip())


def parse_gcode_header(gcode_path: Path) -> dict[str, str]:
    patterns = {
        "slicer": re.compile(r"generated by (?P<value>.+)", re.IGNORECASE),
        "print_time": re.compile(r"estimated printing time(?: \(normal mode\))?\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "total_layers": re.compile(r"total layer number\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "filament_weight_g": re.compile(r"filament used \[g\]\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "max_z_height": re.compile(r"max_z_height\s*=\s*(?P<value>.+)", re.IGNORECASE),
        "filament_slots": re.compile(r"filament_ids\s*=\s*(?P<value>.+)", re.IGNORECASE),
    }
    extracted: dict[str, str] = {}
    with gcode_path.open("r", encoding="utf-8", errors="ignore") as handle:
        for index, raw_line in enumerate(handle):
            if index > 350:
                break
            line = raw_line.strip().lstrip("; ")
            for key, pattern in patterns.items():
                if key in extracted:
                    continue
                match = pattern.search(line)
                if match:
                    extracted[key] = match.group("value").strip()
    return extracted


@functools.lru_cache(maxsize=256)
def build_preview_payload(gcode_path_text: str) -> dict[str, object]:
    gcode_path = Path(gcode_path_text)
    absolute_moves = True
    absolute_extrusion = True
    current_x = 0.0
    current_y = 0.0
    current_z = 0.0
    current_e = 0.0
    current_tool = 0
    segments: list[tuple[float, float, float, float, int]] = []
    layer_heights: set[float] = set()

    with gcode_path.open("r", encoding="utf-8", errors="ignore") as handle:
        for raw_line in handle:
            line = raw_line.split(";", 1)[0].strip()
            if not line:
                continue
            command = line.split()[0].upper()
            if command == "G90":
                absolute_moves = True
                continue
            if command == "G91":
                absolute_moves = False
                continue
            if command == "M82":
                absolute_extrusion = True
                continue
            if command == "M83":
                absolute_extrusion = False
                continue
            if command.startswith("T") and command[1:].isdigit():
                current_tool = int(command[1:]) % len(SVG_PALETTE)
                continue
            if command not in {"G0", "G1"}:
                continue

            parameters = {match.group(1): float(match.group(2)) for match in re.finditer(r"([XYZE])([-+]?\d*\.?\d+)", line, flags=re.IGNORECASE)}
            next_x = current_x
            next_y = current_y
            next_z = current_z
            next_e = current_e

            if "X" in parameters:
                next_x = parameters["X"] if absolute_moves else current_x + parameters["X"]
            if "Y" in parameters:
                next_y = parameters["Y"] if absolute_moves else current_y + parameters["Y"]
            if "Z" in parameters:
                next_z = parameters["Z"] if absolute_moves else current_z + parameters["Z"]
            if "E" in parameters:
                next_e = parameters["E"] if absolute_extrusion else current_e + parameters["E"]

            extrusion_delta = next_e - current_e
            if extrusion_delta > 0 and (next_x != current_x or next_y != current_y):
                layer_heights.add(round(next_z, 3))
                segments.append((current_x, current_y, next_x, next_y, current_tool))
                if len(segments) >= 25000:
                    break

            current_x = next_x
            current_y = next_y
            current_z = next_z
            current_e = next_e

    if not segments:
        return {"svg": empty_preview_svg(), "segment_count": 0, "layer_count": 0}

    min_x = min(min(segment[0], segment[2]) for segment in segments)
    max_x = max(max(segment[0], segment[2]) for segment in segments)
    min_y = min(min(segment[1], segment[3]) for segment in segments)
    max_y = max(max(segment[1], segment[3]) for segment in segments)

    width = max(max_x - min_x, 1.0)
    height = max(max_y - min_y, 1.0)
    canvas = 920.0
    margin = 30.0
    scale = min((canvas - (margin * 2)) / width, (canvas - (margin * 2)) / height)

    def project(point_x: float, point_y: float) -> tuple[float, float]:
        projected_x = margin + ((point_x - min_x) * scale)
        projected_y = canvas - margin - ((point_y - min_y) * scale)
        return projected_x, projected_y

    lines: list[str] = []
    for start_x, start_y, end_x, end_y, tool in segments:
        projected_start = project(start_x, start_y)
        projected_end = project(end_x, end_y)
        color = SVG_PALETTE[tool % len(SVG_PALETTE)]
        lines.append(
            f'<line x1="{projected_start[0]:.2f}" y1="{projected_start[1]:.2f}" '
            f'x2="{projected_end[0]:.2f}" y2="{projected_end[1]:.2f}" '
            f'stroke="{color}" stroke-width="1.2" stroke-linecap="round" opacity="0.9" />'
        )

    svg = "".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 920 920" role="img" aria-label="G-code preview">',
            '<rect x="0" y="0" width="920" height="920" fill="#f6f1e8" rx="24" ry="24" />',
            '<rect x="20" y="20" width="880" height="880" fill="#fffaf2" stroke="#d8c9b6" stroke-width="2" rx="20" ry="20" />',
            *lines,
            '</svg>',
        ]
    )
    return {"svg": svg, "segment_count": len(segments), "layer_count": len(layer_heights)}


def empty_preview_svg() -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 920 920" role="img" aria-label="No preview">'
        '<rect x="0" y="0" width="920" height="920" fill="#f6f1e8" rx="24" ry="24" />'
        '<text x="460" y="460" text-anchor="middle" font-family="Segoe UI, sans-serif" font-size="28" fill="#5f5a52">'
        'No extrusion preview available'
        '</text>'
        '</svg>'
    )


class DecisionStore:
    def __init__(self, export_path: Path, manifest_path: Path, manifest_writeback: bool) -> None:
        self.export_path = export_path
        self.manifest_path = manifest_path
        self.manifest_writeback = manifest_writeback
        self.entries: dict[str, dict[str, object]] = {}
        self.load()

    def load(self) -> None:
        if not self.export_path.exists():
            return
        payload = load_json(self.export_path)
        for entry in payload.get("entries", []):
            gcode_name = entry.get("gcode_name")
            if not gcode_name:
                continue
            normalized = self._normalize_entry(entry)
            if normalized:
                self.entries[gcode_name] = normalized

    def _normalize_entry(self, entry: dict[str, object]) -> dict[str, object] | None:
        disposition = normalize_disposition(str(entry.get("disposition") or ""))
        note = str(entry.get("note") or "").strip()
        archive_id = parse_archive_id(entry.get("archive_id")) if entry.get("archive_id") not in (None, "") else None
        related_relative_path = str(entry.get("related_relative_path") or "").strip() or None
        if not disposition and archive_id is None and not note and not related_relative_path:
            return None
        normalized: dict[str, object] = {
            "disposition": disposition,
            "archive_id": archive_id,
            "note": note,
            "related_relative_path": related_relative_path,
            "updated_at": str(entry.get("updated_at") or utc_now_iso()),
        }
        return normalized

    def get(self, gcode_name: str) -> dict[str, object] | None:
        return self.entries.get(gcode_name)

    def save(self, gcode_name: str, disposition: str | None, archive_id: int | None, note: str, related_relative_path: str | None) -> dict[str, object] | None:
        entry = self._normalize_entry(
            {
                "gcode_name": gcode_name,
                "disposition": disposition,
                "archive_id": archive_id,
                "note": note,
                "related_relative_path": related_relative_path,
                "updated_at": utc_now_iso(),
            }
        )
        if entry is None:
            self.entries.pop(gcode_name, None)
        else:
            self.entries[gcode_name] = entry
        self.write_export()
        if self.manifest_writeback:
            self.write_manifest()
        return self.entries.get(gcode_name)

    def export_payload(self) -> dict[str, object]:
        counts = {key: 0 for key in DISPOSITIONS}
        for entry in self.entries.values():
            disposition = entry.get("disposition")
            if disposition in counts:
                counts[disposition] += 1
        rows = []
        for gcode_name in sorted(self.entries):
            row = {"gcode_name": gcode_name, **self.entries[gcode_name]}
            rows.append(row)
        return {
            "generated_at": utc_now_iso(),
            "manifest_writeback_enabled": self.manifest_writeback,
            "entry_count": len(rows),
            "disposition_counts": counts,
            "entries": rows,
        }

    def write_export(self) -> None:
        write_json(self.export_path, self.export_payload())

    def write_manifest(self) -> None:
        manifest = load_json(self.manifest_path)
        secondary = manifest.setdefault("secondary_artifact_analysis", {})
        cache_section = secondary.setdefault("cache_secondary_artifacts", {})
        payload = self.export_payload()
        cache_section["manual_triage_decisions"] = {
            "updated_at": payload["generated_at"],
            "decision_export_path": str(self.export_path).replace("\\", "/"),
            "entry_count": payload["entry_count"],
            "disposition_counts": payload["disposition_counts"],
            "entries": payload["entries"],
        }
        write_json(self.manifest_path, manifest)


class ForensicsDataset:
    def __init__(self, source_root: Path, manifest_path: Path, pairings_path: Path, decision_store: DecisionStore) -> None:
        self.source_root = source_root
        self.cache_dir = source_root / "cache"
        self.image_dir = source_root / "image"
        self.manifest = load_json(manifest_path)
        self.pairings = load_json(pairings_path)
        self.decision_store = decision_store
        self.manifest_candidates = {
            candidate["relative_path"].replace("\\", "/"): candidate
            for candidate in self.manifest.get("candidates", [])
        }
        self.image_inventory = [
            {
                "name": image_path.name,
                "timestamp": datetime.fromtimestamp(image_path.stat().st_mtime, tz=timezone.utc),
                "path": image_path,
            }
            for image_path in sorted(self.image_dir.glob("*.png"))
        ]
        self.records = self._build_records()
        self.record_map = {record["gcode_name"]: record for record in self.records}
        self.summary = self._build_summary()

    def _build_records(self) -> list[dict[str, object]]:
        records: list[dict[str, object]] = []
        for row in self.pairings:
            gcode_name = row["gcode"]
            gcode_path = self.cache_dir / gcode_name
            exact_matches = [normalize_cache_relative_path(item) for item in normalize_match_values(row.get("exact_3mf_matches"))]
            near_matches = [normalize_cache_relative_path(item) for item in normalize_match_values(row.get("near_time_3mf_matches"))]
            if exact_matches:
                classification = "exact_3mf_match"
            elif near_matches:
                classification = "near_time_3mf_match"
            else:
                classification = "ambiguous"

            if classification != "ambiguous":
                recovery_bucket = "likely_secondary_to_represented_3mf"
            elif row["prefix"] in GENERIC_MULTI_PLATE_PREFIXES:
                recovery_bucket = "ambiguous_generic_multi_plate_groups"
            else:
                recovery_bucket = "ambiguous_named_singletons_or_small_groups"

            manifest_links: list[dict[str, object]] = []
            linked_paths = exact_matches or near_matches
            for relative_path in linked_paths:
                candidate = self.manifest_candidates.get(relative_path)
                if not candidate:
                    continue
                archive_id = candidate.get("created_archive_id") or candidate.get("matched_archive_id")
                manifest_links.append(
                    {
                        "relative_path": relative_path,
                        "processing_bucket": candidate.get("processing_bucket"),
                        "import_status": candidate.get("import_status"),
                        "archive_id": archive_id,
                        "batch_id": candidate.get("batch_id"),
                    }
                )

            image_matches = []
            last_write = parse_timestamp(row.get("last_write"))
            if last_write is not None:
                for image in self.image_inventory:
                    delta_seconds = abs((image["timestamp"] - last_write).total_seconds())
                    if delta_seconds <= 120:
                        image_matches.append(
                            {
                                "name": image["name"],
                                "seconds_delta": int(delta_seconds),
                            }
                        )
                image_matches.sort(key=lambda item: (item["seconds_delta"], item["name"]))

            header_metadata = parse_gcode_header(gcode_path) if gcode_path.exists() else {}
            records.append(
                {
                    "gcode_name": gcode_name,
                    "gcode_path": str(gcode_path),
                    "prefix": row["prefix"],
                    "classification": classification,
                    "recovery_bucket": recovery_bucket,
                    "size_bytes": row["size"],
                    "size_human": human_size(int(row["size"])),
                    "last_write": row["last_write"],
                    "exact_matches": exact_matches,
                    "near_matches": near_matches,
                    "manifest_links": manifest_links,
                    "image_matches": image_matches[:8],
                    "header_metadata": header_metadata,
                    "has_gcode": gcode_path.exists(),
                    "decision": self.decision_store.get(gcode_name),
                }
            )
        return sorted(records, key=lambda item: (item["classification"], item["recovery_bucket"], item["gcode_name"]))

    def _build_summary(self) -> dict[str, int]:
        summary: dict[str, int] = {
            "total": len(self.records),
            "exact_3mf_match": 0,
            "near_time_3mf_match": 0,
            "ambiguous": 0,
            "likely_secondary_to_represented_3mf": 0,
            "ambiguous_generic_multi_plate_groups": 0,
            "ambiguous_named_singletons_or_small_groups": 0,
            "Keep": 0,
            "Ignore": 0,
            "Investigate": 0,
        }
        for record in self.records:
            summary[record["classification"]] += 1
            summary[record["recovery_bucket"]] += 1
            decision = record.get("decision") or {}
            disposition = decision.get("disposition")
            if disposition in summary:
                summary[disposition] += 1
        return summary

    def filtered_records(self, view: str) -> list[dict[str, object]]:
        if view == "all":
            return self.records
        if view in DISPOSITIONS:
            return [record for record in self.records if (record.get("decision") or {}).get("disposition") == view]
        return [record for record in self.records if record["classification"] == view or record["recovery_bucket"] == view]

    def update_decision(self, gcode_name: str, disposition: str | None, archive_id: int | None, note: str, related_relative_path: str | None) -> dict[str, object] | None:
        entry = self.decision_store.save(gcode_name, disposition, archive_id, note, related_relative_path)
        if gcode_name in self.record_map:
            self.record_map[gcode_name]["decision"] = entry
        self.summary = self._build_summary()
        return entry


def render_page(dataset: ForensicsDataset, view: str, selected_name: str | None, writeback_enabled: bool, export_path: Path) -> str:
    visible_records = dataset.filtered_records(view)
    selected_record = dataset.record_map.get(selected_name or "")
    if selected_record not in visible_records:
        selected_record = visible_records[0] if visible_records else None

    filter_links = [
        ("ambiguous", f"Ambiguous ({dataset.summary['ambiguous']})"),
        ("Investigate", f"Investigate ({dataset.summary['Investigate']})"),
        ("Keep", f"Keep ({dataset.summary['Keep']})"),
        ("Ignore", f"Ignore ({dataset.summary['Ignore']})"),
        ("ambiguous_named_singletons_or_small_groups", f"Named / small groups ({dataset.summary['ambiguous_named_singletons_or_small_groups']})"),
        ("ambiguous_generic_multi_plate_groups", f"Generic groups ({dataset.summary['ambiguous_generic_multi_plate_groups']})"),
        ("near_time_3mf_match", f"Near-time matches ({dataset.summary['near_time_3mf_match']})"),
        ("exact_3mf_match", f"Exact matches ({dataset.summary['exact_3mf_match']})"),
        ("all", f"All ({dataset.summary['total']})"),
    ]
    filter_markup = "".join(
        f'<a class="filter {"active" if key == view else ""}" href="/?{urlencode({"view": key})}">{html.escape(label)}</a>'
        for key, label in filter_links
    )

    list_markup = "".join(render_list_item(record, view, selected_record) for record in visible_records) or '<div class="empty">No records for this filter.</div>'
    detail_markup = render_detail_panel(selected_record, view, writeback_enabled)
    export_href = "/export/decisions.json"
    writeback_text = "enabled" if writeback_enabled else "disabled"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>G-code Forensics Viewer</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f3efe8;
      --panel: #fffaf2;
      --panel-strong: #f8f0e2;
      --border: #d6c7b2;
      --ink: #2d2a26;
      --muted: #6c655c;
      --accent: #006d77;
      --accent-soft: #d7eceb;
      --warn: #b45309;
      --warn-soft: #fce7c7;
      --good: #1d6f42;
      --good-soft: #dbeee2;
      --bad: #915c00;
    }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; font-family: "Segoe UI", sans-serif; background: radial-gradient(circle at top left, #fff7eb 0, var(--bg) 45%, #ebe2d2 100%); color: var(--ink); }}
    .layout {{ display: grid; grid-template-columns: 360px 1fr; min-height: 100vh; }}
    .sidebar {{ border-right: 1px solid var(--border); background: rgba(255, 250, 242, 0.92); backdrop-filter: blur(8px); padding: 20px; overflow: auto; }}
    .content {{ padding: 24px; overflow: auto; }}
    h1, h2, h3, p {{ margin-top: 0; }}
    .toolbar {{ display: grid; gap: 10px; margin-bottom: 16px; }}
    .toolbar a {{ color: var(--accent); text-decoration: none; font-weight: 600; }}
    .muted {{ color: var(--muted); }}
    .filters {{ display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }}
    .filter {{ padding: 8px 12px; border-radius: 999px; text-decoration: none; color: var(--ink); background: var(--panel-strong); border: 1px solid transparent; font-size: 13px; }}
    .filter.active {{ border-color: var(--accent); background: var(--accent-soft); color: var(--accent); }}
    .record-list {{ display: grid; gap: 10px; }}
    .record {{ display: block; padding: 12px 14px; border: 1px solid var(--border); border-radius: 14px; text-decoration: none; color: inherit; background: var(--panel); }}
    .record.active {{ border-color: var(--accent); box-shadow: 0 0 0 2px rgba(0, 109, 119, 0.12); }}
    .record-name {{ font-weight: 600; font-size: 13px; line-height: 1.35; margin-bottom: 8px; word-break: break-word; }}
    .badges {{ display: flex; gap: 6px; flex-wrap: wrap; }}
    .badge {{ font-size: 11px; padding: 4px 8px; border-radius: 999px; background: var(--panel-strong); color: var(--muted); }}
    .badge.emphasis {{ background: var(--accent-soft); color: var(--accent); }}
    .badge.warn {{ background: var(--warn-soft); color: var(--warn); }}
    .badge.keep {{ background: var(--good-soft); color: var(--good); }}
    .badge.ignore {{ background: #f6e7ce; color: var(--bad); }}
    .badge.investigate {{ background: #ece3fa; color: #5c3f85; }}
    .hero {{ display: grid; grid-template-columns: minmax(360px, 700px) minmax(280px, 1fr); gap: 20px; align-items: start; }}
    .panel {{ background: rgba(255, 250, 242, 0.92); border: 1px solid var(--border); border-radius: 18px; padding: 18px; }}
    .panel img {{ max-width: 100%; height: auto; display: block; }}
    .meta-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin: 16px 0; }}
    .meta {{ background: var(--panel); border: 1px solid var(--border); border-radius: 14px; padding: 12px; }}
    .meta-label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); margin-bottom: 6px; }}
    .meta-value {{ font-weight: 600; line-height: 1.4; word-break: break-word; }}
    .section {{ margin-top: 20px; }}
    .section ul {{ margin: 10px 0 0; padding-left: 18px; }}
    .image-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }}
    .image-card {{ background: var(--panel); border: 1px solid var(--border); border-radius: 14px; overflow: hidden; }}
    .image-card figcaption {{ padding: 10px 12px; font-size: 12px; color: var(--muted); }}
    .empty {{ color: var(--muted); padding: 16px; border: 1px dashed var(--border); border-radius: 14px; }}
    .decision-form {{ display: grid; gap: 12px; }}
    .decision-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }}
    label {{ display: grid; gap: 6px; font-size: 13px; color: var(--muted); }}
    input, select, textarea, button {{ font: inherit; }}
    input, select, textarea {{ width: 100%; padding: 10px 12px; border-radius: 12px; border: 1px solid var(--border); background: #fffdf8; color: var(--ink); }}
    textarea {{ min-height: 96px; resize: vertical; }}
    button {{ padding: 10px 14px; border-radius: 999px; border: 0; cursor: pointer; background: var(--accent); color: white; font-weight: 600; }}
    button.secondary {{ background: var(--panel-strong); color: var(--ink); border: 1px solid var(--border); }}
    .status {{ font-size: 13px; color: var(--muted); }}
    .viewer-shell {{ display: grid; gap: 12px; }}
    .viewer-canvas-wrap {{ display: none; height: 560px; background: #1a1a1a; border-radius: 14px; overflow: hidden; }}
    .viewer-canvas-wrap.active {{ display: block; }}
    .viewer-canvas-wrap canvas {{ width: 100%; height: 100%; display: block; }}
    pre {{ margin: 0; white-space: pre-wrap; word-break: break-word; font-size: 12px; line-height: 1.5; background: #f5ede0; border-radius: 14px; padding: 14px; border: 1px solid var(--border); }}
    @media (max-width: 1080px) {{
      .layout {{ grid-template-columns: 1fr; }}
      .sidebar {{ border-right: 0; border-bottom: 1px solid var(--border); }}
      .hero {{ grid-template-columns: 1fr; }}
    }}
  </style>
</head>
<body>
  <div class="layout">
    <aside class="sidebar">
      <h1>G-code Forensics Viewer</h1>
      <p>Local triage UI for cache `.gcode` artifacts with static preview, optional upstream-style interactive rendering, nearby images, and manifest-aware disposition tracking.</p>
      <div class="toolbar">
        <div class="muted">Decision export: {html.escape(str(export_path).replace('\\', '/'))}</div>
        <div class="muted">Manifest writeback: {writeback_text}</div>
        <a href="{export_href}">Download decision export JSON</a>
      </div>
      <div class="filters">{filter_markup}</div>
      <div class="record-list">{list_markup}</div>
    </aside>
    <main class="content">{detail_markup}</main>
  </div>
</body>
</html>"""


def disposition_badge(disposition: str | None) -> str:
    if disposition == "Keep":
        return '<span class="badge keep">Keep</span>'
    if disposition == "Ignore":
        return '<span class="badge ignore">Ignore</span>'
    if disposition == "Investigate":
        return '<span class="badge investigate">Investigate</span>'
    return '<span class="badge">Undecided</span>'


def render_list_item(record: dict[str, object], view: str, selected_record: dict[str, object] | None) -> str:
    selected_name = selected_record["gcode_name"] if selected_record else None
    href = "/?" + urlencode({"view": view, "selected": record["gcode_name"]})
    decision = record.get("decision") or {}
    badges = [
        f'<span class="badge emphasis">{html.escape(str(record["classification"]))}</span>',
        f'<span class="badge">{html.escape(str(record["recovery_bucket"]))}</span>',
        disposition_badge(decision.get("disposition")),
    ]
    if record["image_matches"]:
        badges.append(f'<span class="badge warn">{len(record["image_matches"])} nearby image(s)</span>')
    return (
        f'<a class="record {"active" if record["gcode_name"] == selected_name else ""}" href="{href}">'
        f'<div class="record-name">{html.escape(str(record["gcode_name"]))}</div>'
        f'<div class="badges">{"".join(badges)}</div>'
        '</a>'
    )


def render_detail_panel(record: dict[str, object] | None, view: str, writeback_enabled: bool) -> str:
    if record is None:
        return '<div class="panel empty">No matching record.</div>'
    preview_info = build_preview_payload(str(record["gcode_path"])) if record["has_gcode"] else {"segment_count": 0, "layer_count": 0}
    decision = record.get("decision") or {}
    related_relative_path = decision.get("related_relative_path") or ""
    manifest_links = record["manifest_links"]
    image_markup = "".join(
        f'<figure class="image-card"><img src="/image/{quote(image["name"])}" alt="{html.escape(image["name"])}" />'
        f'<figcaption>{html.escape(image["name"])}<br />±{image["seconds_delta"]}s</figcaption></figure>'
        for image in record["image_matches"]
    ) or '<div class="empty">No nearby image within the current 2-minute correlation window.</div>'
    manifest_markup = "".join(
        '<li>'
        f'{html.escape(link["relative_path"])}: '
        f'{html.escape(str(link["import_status"]))}'
        + (f' (archive {html.escape(str(link["archive_id"]))})' if link.get("archive_id") else "")
        + '</li>'
        for link in manifest_links
    ) or '<li>No related cache 3mf candidate was identified.</li>'
    related_options = [
        '<option value="">No linked cache 3mf</option>',
        *[
            f'<option value="{html.escape(link["relative_path"])}" {"selected" if link["relative_path"] == related_relative_path else ""}>{html.escape(link["relative_path"])} ({html.escape(str(link["import_status"]))})</option>'
            for link in manifest_links
        ],
    ]
    metadata_markup = "".join(
        f'<div class="meta"><div class="meta-label">{html.escape(label)}</div><div class="meta-value">{html.escape(value)}</div></div>'
        for label, value in [
            ("Classification", str(record["classification"])),
            ("Recovery Bucket", str(record["recovery_bucket"])),
            ("Disposition", str(decision.get("disposition") or "Undecided")),
            ("Archive ID", str(decision.get("archive_id") or "")),
            ("Last Write", str(record["last_write"])),
            ("File Size", str(record["size_human"])),
            ("Static Preview Segments", str(preview_info["segment_count"])),
            ("Static Preview Layers", str(preview_info["layer_count"])),
        ]
    )
    preview_src = "/preview.svg?" + urlencode({"gcode": record["gcode_name"]})
    interactive_notice = "Writes decisions into the export file only." if not writeback_enabled else "Writes decisions into the export file and into secondary_artifact_analysis.manual_triage_decisions in the manifest."
    return f"""
<div class="panel">
  <h2>{html.escape(str(record['gcode_name']))}</h2>
  <div class="badges">
    <span class="badge emphasis">{html.escape(str(record['classification']))}</span>
    <span class="badge">{html.escape(str(record['recovery_bucket']))}</span>
    {disposition_badge(decision.get('disposition'))}
    <span class="badge warn">{len(record['image_matches'])} nearby image(s)</span>
  </div>
  <div class="meta-grid">{metadata_markup}</div>
  <div class="hero">
    <section class="panel viewer-shell">
      <h3>Static Toolpath Preview</h3>
      <img src="{preview_src}" alt="Toolpath preview for {html.escape(str(record['gcode_name']))}" />
      <button class="secondary" type="button" id="load-3d-viewer">Load Optional 3D Viewer</button>
      <div class="status">Uses the same `gcode-preview` library as upstream Bambuddy, but only loads when requested.</div>
      <div class="viewer-canvas-wrap" id="interactive-viewer-wrap">
        <canvas id="interactive-viewer-canvas"></canvas>
      </div>
      <div class="status" id="interactive-viewer-status"></div>
    </section>
    <section class="panel">
      <h3>Header Metadata</h3>
      <pre>{escape_json_for_html(record['header_metadata'])}</pre>
    </section>
  </div>
  <section class="section panel">
    <h3>Disposition</h3>
    <div class="status">{html.escape(interactive_notice)}</div>
    <form class="decision-form" id="decision-form">
      <div class="decision-grid">
        <label>
          Disposition
          <select name="disposition">
            <option value="">Undecided</option>
            <option value="Keep" {"selected" if decision.get('disposition') == 'Keep' else ''}>Keep</option>
            <option value="Ignore" {"selected" if decision.get('disposition') == 'Ignore' else ''}>Ignore</option>
            <option value="Investigate" {"selected" if decision.get('disposition') == 'Investigate' else ''}>Investigate</option>
          </select>
        </label>
        <label>
          Existing Archive ID
          <input name="archive_id" type="number" min="1" value="{html.escape(str(decision.get('archive_id') or ''))}" />
        </label>
        <label>
          Related Cache 3MF
          <select name="related_relative_path">
            {''.join(related_options)}
          </select>
        </label>
      </div>
      <label>
        Notes
        <textarea name="note">{html.escape(str(decision.get('note') or ''))}</textarea>
      </label>
      <div class="badges">
        <button type="submit">Save Decision</button>
        <a class="filter" href="/export/decisions.json">Export Decisions</a>
      </div>
      <div class="status" id="decision-status"></div>
    </form>
  </section>
  <section class="section">
    <h3>Related Cache 3MF Status</h3>
    <ul>{manifest_markup}</ul>
  </section>
  <section class="section">
    <h3>Nearby Images</h3>
    <div class="image-grid">{image_markup}</div>
  </section>
</div>
<script>
  const selectedGcode = {json.dumps(record['gcode_name'])};
  const decisionForm = document.getElementById('decision-form');
  const decisionStatus = document.getElementById('decision-status');
  const loadViewerButton = document.getElementById('load-3d-viewer');
  const viewerWrap = document.getElementById('interactive-viewer-wrap');
  const viewerCanvas = document.getElementById('interactive-viewer-canvas');
  const viewerStatus = document.getElementById('interactive-viewer-status');
  let viewerLoaded = false;
  let activePreview = null;

  function setDecisionStatus(message, isError = false) {{
    decisionStatus.textContent = message;
    decisionStatus.style.color = isError ? '#b42318' : '#2d2a26';
  }}

  decisionForm.addEventListener('submit', async (event) => {{
    event.preventDefault();
    const formData = new FormData(decisionForm);
    const payload = {{
      gcode_name: selectedGcode,
      disposition: formData.get('disposition') || '',
      archive_id: formData.get('archive_id') || '',
      related_relative_path: formData.get('related_relative_path') || '',
      note: formData.get('note') || ''
    }};
    setDecisionStatus('Saving decision...');
    try {{
      const response = await fetch('/api/decision', {{
        method: 'POST',
        headers: {{ 'Content-Type': 'application/json' }},
        body: JSON.stringify(payload)
      }});
      const data = await response.json();
      if (!response.ok) {{
        throw new Error(data.error || 'Failed to save decision');
      }}
      setDecisionStatus(data.message || 'Decision saved.');
      window.setTimeout(() => window.location.reload(), 350);
    }} catch (error) {{
      setDecisionStatus(error.message || 'Failed to save decision.', true);
    }}
  }});

    let gcodePreviewModulePromise = null;
    async function ensureGcodePreviewLibrary() {{
        if (!gcodePreviewModulePromise) {{
            gcodePreviewModulePromise = import({json.dumps(GCODE_PREVIEW_MODULE_URL)}).catch(error => {{
                gcodePreviewModulePromise = null;
                throw error;
            }});
        }}
        const module = await gcodePreviewModulePromise;
        if (!module?.WebGLPreview) {{
            throw new Error('gcode-preview module did not expose WebGLPreview.');
        }}
        return module;
    }}

  loadViewerButton.addEventListener('click', async () => {{
    if (viewerLoaded) {{
      viewerWrap.classList.toggle('active');
      viewerStatus.textContent = viewerWrap.classList.contains('active') ? 'Interactive viewer visible.' : 'Interactive viewer hidden.';
      return;
    }}
    viewerStatus.textContent = 'Loading optional 3D viewer...';
    try {{
    const GCodePreview = await ensureGcodePreviewLibrary();
      const response = await fetch('/gcode?' + new URLSearchParams({{ gcode: selectedGcode }}));
      if (!response.ok) {{
        throw new Error('Failed to load raw G-code for interactive preview.');
      }}
      const gcode = await response.text();
      viewerWrap.classList.add('active');
      viewerCanvas.width = viewerWrap.clientWidth;
      viewerCanvas.height = viewerWrap.clientHeight;
            activePreview = new GCodePreview.WebGLPreview({{
        canvas: viewerCanvas,
        backgroundColor: 0x1a1a1a,
        extrusionColor: {json.dumps(SVG_PALETTE)},
        disableGradient: true,
        lineWidth: 2,
        renderTravel: false,
        renderExtrusion: true,
      }});
      activePreview.processGCode(gcode);
      activePreview.render();
      viewerLoaded = true;
      viewerStatus.textContent = 'Interactive viewer loaded.';
      loadViewerButton.textContent = 'Toggle Optional 3D Viewer';
    }} catch (error) {{
      viewerStatus.textContent = error.message || 'Failed to load interactive viewer.';
    }}
  }});
</script>
"""


class ForensicsHandler(BaseHTTPRequestHandler):
    dataset: ForensicsDataset
    writeback_enabled: bool
    export_path: Path

    def send_text(self, status_code: int, content_type: str, body: bytes) -> None:
        self.send_response(status_code)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def send_json(self, status_code: int, payload: dict[str, object]) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_text(status_code, "application/json; charset=utf-8", body)

    def do_GET(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        if parsed.path == "/":
            params = parse_qs(parsed.query)
            view = params.get("view", ["ambiguous"])[0]
            selected = params.get("selected", [None])[0]
            body = render_page(self.dataset, view, selected, self.writeback_enabled, self.export_path).encode("utf-8")
            self.send_text(200, "text/html; charset=utf-8", body)
            return

        if parsed.path == "/preview.svg":
            params = parse_qs(parsed.query)
            gcode_name = params.get("gcode", [""])[0]
            record = self.dataset.record_map.get(gcode_name)
            svg = empty_preview_svg() if record is None else build_preview_payload(str(record["gcode_path"]))["svg"]
            self.send_text(200, "image/svg+xml; charset=utf-8", str(svg).encode("utf-8"))
            return

        if parsed.path == "/gcode":
            params = parse_qs(parsed.query)
            gcode_name = params.get("gcode", [""])[0]
            record = self.dataset.record_map.get(gcode_name)
            if record is None:
                self.send_error(404, "G-code not found")
                return
            gcode_path = Path(record["gcode_path"])
            if not gcode_path.exists():
                self.send_error(404, "G-code file missing")
                return
            self.send_text(200, "text/plain; charset=utf-8", gcode_path.read_text(encoding="utf-8", errors="ignore").encode("utf-8"))
            return

        if parsed.path == "/export/decisions.json":
            payload = self.dataset.decision_store.export_payload()
            body = json.dumps(payload, indent=2, ensure_ascii=False).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Disposition", 'attachment; filename="gcode_forensics_decisions.json"')
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        if parsed.path.startswith("/image/"):
            image_name = Path(parsed.path.removeprefix("/image/")).name
            image_path = self.dataset.image_dir / image_name
            if not image_path.exists():
                self.send_error(404, "Image not found")
                return
            content_type, _ = mimetypes.guess_type(image_path.name)
            self.send_text(200, content_type or "application/octet-stream", image_path.read_bytes())
            return

        self.send_error(404, "Not found")

    def do_POST(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        if parsed.path != "/api/decision":
            self.send_error(404, "Not found")
            return
        content_length = int(self.headers.get("Content-Length", "0"))
        raw_body = self.rfile.read(content_length)
        try:
            payload = json.loads(raw_body.decode("utf-8"))
            gcode_name = str(payload.get("gcode_name") or "").strip()
            if not gcode_name or gcode_name not in self.dataset.record_map:
                raise ValueError("Unknown gcode name.")
            disposition = normalize_disposition(str(payload.get("disposition") or ""))
            archive_id = parse_archive_id(payload.get("archive_id")) if payload.get("archive_id") not in (None, "") else None
            note = str(payload.get("note") or "").strip()
            related_relative_path = str(payload.get("related_relative_path") or "").strip() or None
            entry = self.dataset.update_decision(gcode_name, disposition, archive_id, note, related_relative_path)
        except Exception as exc:  # noqa: BLE001
            self.send_json(400, {"error": str(exc)})
            return
        message = "Decision saved to export file."
        if self.writeback_enabled:
            message = "Decision saved to export file and manifest."
        self.send_json(200, {"message": message, "entry": entry})

    def log_message(self, format_string: str, *args) -> None:
        return


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Launch a local viewer for Bambuddy cache G-code forensics.")
    parser.add_argument("--source-root", default="bambuddy/Backup SD Card - 2026-04-03", help="Root of the SD-card backup.")
    parser.add_argument("--manifest", default="bambuddy/backfill-state/archive_backfill_manifest_v2.json", help="Manifest path used for import/archive status.")
    parser.add_argument("--pairings", default="tmp/cache_gcode_pairing_analysis.json", help="Pairing analysis JSON path.")
    parser.add_argument("--decision-output", default="tmp/gcode_forensics_decisions.json", help="Export path for Keep/Ignore/Investigate decisions.")
    parser.add_argument("--manifest-writeback", action="store_true", help="Also write saved decisions back into the manifest under secondary_artifact_analysis.")
    parser.add_argument("--host", default="127.0.0.1", help="HTTP bind host.")
    parser.add_argument("--port", type=int, default=8765, help="HTTP bind port.")
    parser.add_argument("--no-browser", action="store_true", help="Do not automatically open a browser window.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    export_path = Path(args.decision_output)
    decision_store = DecisionStore(export_path, Path(args.manifest), args.manifest_writeback)
    dataset = ForensicsDataset(Path(args.source_root), Path(args.manifest), Path(args.pairings), decision_store)
    ForensicsHandler.dataset = dataset
    ForensicsHandler.writeback_enabled = args.manifest_writeback
    ForensicsHandler.export_path = export_path
    server = ThreadingHTTPServer((args.host, args.port), ForensicsHandler)
    url = f"http://{args.host}:{args.port}/?view=ambiguous"
    print(f"Serving G-code forensics viewer at {url}")
    print(f"Decision export path: {export_path}")
    if args.manifest_writeback:
        print(f"Manifest writeback enabled: {args.manifest}")
    if not args.no_browser:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())